### PR TITLE
BUCK file parser

### PR DESCRIPTION
**Pull request by JonoYang**
This enhances the BUCK file parser found in `packagedcode/build.py`. We are able to collect the build target names and licenses of the different build rules defined in a BUCK file.

### CODE REVIEW

**Comment by pombredanne** [comment]
`api_data_url`, `purl`, `repository_download_url` and `repository_homepage_url` are missing from consolidated components and are stripped by the consolidate option from existing package records..... that's really weird. 
This is where these properties are serialized: https://github.com/nexB/scancode-toolkit/blob/1678-parse-buck-files/src/packagedcode/models.py#L299

It could be that in https://github.com/nexB/scancode-toolkit/blob/1678-parse-buck-files/src/scancode/plugin_consolidate.py#L248 the right class is not returned?

**Comment by pombredanne** [comment]
@JonoYang I would like to wrap this and merge it soon enough

**Comment by JonoYang** [comment]
@pombredanne 

> api_data_url, purl, repository_download_url and repository_homepage_url are missing from consolidated components and are stripped by the consolidate option from existing package records..... that's really weird.
This is where these properties are serialized: https://github.com/nexB/scancode-toolkit/blob/1678-parse-buck-files/src/packagedcode/models.py#L299
>
>It could be that in https://github.com/nexB/scancode-toolkit/blob/1678-parse-buck-files/src/scancode/plugin_consolidate.py#L248 the right class is not returned?

I think it's from here https://github.com/nexB/scancode-toolkit/blob/develop/src/packagedcode/__init__.py#L150

I commented out where we remove the fields, and I get this error when running the tests:

```
E             ERROR: failed to run post-scan plugin: consolidate:
E             Traceback (most recent call last):
E               File "/home/jono/nexb/src/scancode-toolkit/src/scancode/cli.py", line 1044, in run_codebase_plugins
E                 plugin.process_codebase(codebase, **kwargs)
E               File "/home/jono/nexb/src/scancode-toolkit/src/scancode/plugin_consolidate.py", line 180, in process_codebase
E                 consolidations.extend(get_consolidated_packages(codebase))
E               File "/home/jono/nexb/src/scancode-toolkit/src/scancode/plugin_consolidate.py", line 248, in get_consolidated_packages
E                 package = get_package_instance(package_data)
E               File "/home/jono/nexb/src/scancode-toolkit/src/packagedcode/__init__.py", line 152, in get_package_instance
E                 return klas(**scan_data)
E             TypeError: __init__() got an unexpected keyword argument 'api_data_url'
```

**Comment by JonoYang** [comment]
@pombredanne A test for the consolidation plugin is failing in this branch. I have fixed this in #1792. I think the BUCK file parser stuff should be alright.

**Comment by pombredanne** [comment]
This has been merged in develop now... but using the CLI. Thank you ++

**Comment by pombredanne** [comment]
@JonoYang I am not sure what these unmerged commits would be if any?

**Pull request closed without merging**
