### PR TITLE
Added new license rules from https://licensebuttons.net/

### LINKED ISSUE #1983: Add license detection rules for https://licensebuttons.net/
## Short Description
https://licensebuttons.net/ contains several buttons to CC licenses that are found as links often enough.
For instance https://licensebuttons.net/p/80x15.png or https://licensebuttons.net/l/GPL/2.0/88x62.png
Each such URL should be added as a license detection rule

## Possible Labels

- new feature

## Select Category

-  Enhancement [x]
-  Add License/Copyright [x]
-  Scan Feature []
-  Packaging []
-  Documentation []
-  Expand Support []
-  Other []

### PR DESCRIPTION
**Pull request by MankaranSingh**
Fixes #1983

### Tasks

* [x] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Rxun [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [x] Commits are in uniquely-named feature branch and has no merge conflicts 📁

I added most of the licence rules, but couldn't find existing licences for the following:

https://licensebuttons.net/l/devnations/
https://licensebuttons.net/l/nc-sa/
https://licensebuttons.net/l/nc-sampling+/
https://licensebuttons.net/l/nc-sampling/
https://licensebuttons.net/l/sa/
https://licensebuttons.net/l/zero/
https://licensebuttons.net/l/nd/
https://licensebuttons.net/l/nd-nc/
https://licensebuttons.net/l/nc/

followup request to #1985

### CODE REVIEW

**Comment by pombredanne** [comment]
Thanks!
So here is the suggestions for the list of URLs you made above that you could not find a license for. There are a few super rare legacy licenses but it is OK to add them.

- For https://licensebuttons.net/l/devnations/ I do not know of ANY actual usage in the wild, and this is legacy, but it does not hurt to add it.  So Add a new license with key `cc-devnations-2.0`  as found at https://creativecommons.org/licenses/devnations/2.0/
Then  add these rules:
  - https://licensebuttons.net/l/devnations/ use `relevance: 100`  and `license_expression: cc-devnations-2.0`
  - https://licensebuttons.net/l/devnations/2.0/ use `relevance: 100`  and `license_expression: cc-devnations-2.0`

- Same for https://licensebuttons.net/l/nc-sampling+/ add a license for https://creativecommons.org/licenses/nc-sampling+/1.0/ `cc-nc-sampling-plus-1.0` and add rules

- Same for https://licensebuttons.net/l/sampling+/  create key `cc-sampling-plus-1.0` with https://creativecommons.org/licenses/sampling+/1.0/ and add rules
 
- Same for  https://licensebuttons.net/l/sampling/  create key `cc-sampling-1.0` with https://creativecommons.org/licenses/sampling/1.0/ and add rules

Add these rules for these other URLs:

- https://licensebuttons.net/l/zero/ -> cc0-1.0
- https://licensebuttons.net/l/zero/1.0/ -> cc0-1.0
- https://licensebuttons.net/l/nd/ -> cc-by-nd-2.0 
- https://licensebuttons.net/l/nd/1.0/ -> cc-by-nd-1.0
- https://licensebuttons.net/l/nd/2.0/ -> cc-by-nd-2.0
- https://licensebuttons.net/l/nd-nc/ -> cc-by-nc-nd-2.0
- https://licensebuttons.net/l/nd-nc/1.0/ -> cc-by-nc-nd-1.0
- https://licensebuttons.net/l/nd-nc/2.0/ -> cc-by-nc-nd-2.0
- https://licensebuttons.net/l/nc/ -> cc-by-nc-2.0
- https://licensebuttons.net/l/nc/1.0/ -> cc-by-nc-nd-1.0
- https://licensebuttons.net/l/nc/2.0/ -> cc-by-nc-nd-2.0
- https://licensebuttons.net/l/nc-sa/ -> cc-by-nc-sa-2.0
- https://licensebuttons.net/l/nc-sa/1.0/ -> cc-by-nc-sa-1.0
- https://licensebuttons.net/l/nc-sa/2.0/ -> cc-by-nc-sa-2.0
- https://licensebuttons.net/l/sa/ -> cc-by-sa-2.0
- https://licensebuttons.net/l/sa/1.0/ -> cc-by-sa-1.0
- https://licensebuttons.net/l/sa/2.0/ -> cc-by-sa-2.0

**Comment by MankaranSingh** [comment]
Sure, ii'L do it tomorrow.

**Comment by MankaranSingh** [comment]
@pombredanne  please have a look.

**Comment by MankaranSingh** [comment]
Tests are failing because rules `ncsa_licensebutton.RULE` and `cc-by-nc-sa-2.0_license_button` are same. What should I do in this case ?

**Comment by MankaranSingh** [comment]
@pombredanne Now only `category` attribute is left to add. 
What would be the exact categories for these licenses:

-  https://creativecommons.org/licenses/devnations/2.0/
-  https://creativecommons.org/licenses/nc-sampling+/1.0/
-  https://creativecommons.org/licenses/sampling+/1.0/
-  https://creativecommons.org/licenses/sampling/1.0/

**Comment by pombredanne** [comment]
@MankaranSingh that would be `Proprietary Free`

**Comment by MankaranSingh** [comment]
@pombredanne all set now, you may review the changes.

**Pull request merged**
