### PR TITLE
Add Github key's test file pairs #1283

### PR DESCRIPTION
**Pull request by sbs2001**
@pombredanne  Here it is!

### CODE REVIEW

**Comment by pombredanne** [comment]
@sbs2001 Thanks. The ticket #1283 should be referenced in the commit title... but I will add that.
Also we prefer to create new, feature-specific branches rather than reuse a `develop` branch

**Comment by pombredanne** [comment]
@sbs2001 Please review and I will merge once I have your OK

**Comment by sbs2001** [comment]
```
====================================
(scancode-toolkit) shivam@shivam-Latitude-D630:~/aboutcode/dev/scancode-toolkit$ pytest -vvs tests/licensedcode/test_detection_datadriven1.py -k github_keys --test-suite=all
==================================================================== test session starts ====================================================================
platform linux2 -- Python 2.7.16, pytest-4.6.3, py-1.8.0, pluggy-0.12.0 -- /home/shivam/aboutcode/dev/scancode-toolkit/bin/python
cachedir: .pytest_cache
rootdir: /home/shivam/aboutcode/dev/scancode-toolkit, inifile: setup.cfg
plugins: cov-2.7.1, rerunfailures-7.0, forked-1.0.2, xdist-1.29.0
collecting 0 items                                                                                                                                          
30 tests selected, 0 tests skipped.
collected 1689 items / 1659 deselected / 30 selected                                                                                                        

tests/licensedcode/test_detection_datadriven1.py::TestLicenseDataDriven::test_detection_licenses_github_keys_afl_3_0_txt <- tests/licensedcode/licensedcode_test_utils.py PASSED
tests/licensedcode/test_detection_datadriven1.py::TestLicenseDataDriven::test_detection_licenses_github_keys_agpl_3_0_txt <- tests/licensedcode/licensedcode_test_utils.py PASSED
tests/licensedcode/test_detection_datadriven1.py::TestLicenseDataDriven::test_detection_licenses_github_keys_apache_2_0_txt <- tests/licensedcode/licensedcode_test_utils.py PASSED
tests/licensedcode/test_detection_datadriven1.py::TestLicenseDataDriven::test_detection_licenses_github_keys_artistic_2_0_txt <- tests/licensedcode/licensedcode_test_utils.py PASSED
tests/licensedcode/test_detection_datadriven1.py::TestLicenseDataDriven::test_detection_licenses_github_keys_bsd_2_clause_txt <- tests/licensedcode/licensedcode_test_utils.py PASSED
tests/licensedcode/test_detection_datadriven1.py::TestLicenseDataDriven::test_detection_licenses_github_keys_bsd_3_clause_clear_txt <- tests/licensedcode/licensedcode_test_utils.py PASSED
tests/licensedcode/test_detection_datadriven1.py::TestLicenseDataDriven::test_detection_licenses_github_keys_bsd_3_clause_txt <- tests/licensedcode/licensedcode_test_utils.py PASSED
tests/licensedcode/test_detection_datadriven1.py::TestLicenseDataDriven::test_detection_licenses_github_keys_bsl_1_0_txt <- tests/licensedcode/licensedcode_test_utils.py PASSED
tests/licensedcode/test_detection_datadriven1.py::TestLicenseDataDriven::test_detection_licenses_github_keys_cc0_1_0_txt <- tests/licensedcode/licensedcode_test_utils.py PASSED
tests/licensedcode/test_detection_datadriven1.py::TestLicenseDataDriven::test_detection_licenses_github_keys_cc_by_4_0_txt <- tests/licensedcode/licensedcode_test_utils.py PASSED
tests/licensedcode/test_detection_datadriven1.py::TestLicenseDataDriven::test_detection_licenses_github_keys_cc_by_sa_4_0_txt <- tests/licensedcode/licensedcode_test_utils.py PASSED
tests/licensedcode/test_detection_datadriven1.py::TestLicenseDataDriven::test_detection_licenses_github_keys_ecl_2_0_txt <- tests/licensedcode/licensedcode_test_utils.py PASSED
tests/licensedcode/test_detection_datadriven1.py::TestLicenseDataDriven::test_detection_licenses_github_keys_epl_1_0_txt <- tests/licensedcode/licensedcode_test_utils.py PASSED
tests/licensedcode/test_detection_datadriven1.py::TestLicenseDataDriven::test_detection_licenses_github_keys_eupl_1_1_txt <- tests/licensedcode/licensedcode_test_utils.py PASSED
tests/licensedcode/test_detection_datadriven1.py::TestLicenseDataDriven::test_detection_licenses_github_keys_gpl_2_0_txt <- tests/licensedcode/licensedcode_test_utils.py PASSED
tests/licensedcode/test_detection_datadriven1.py::TestLicenseDataDriven::test_detection_licenses_github_keys_gpl_3_0_txt <- tests/licensedcode/licensedcode_test_utils.py PASSED
tests/licensedcode/test_detection_datadriven1.py::TestLicenseDataDriven::test_detection_licenses_github_keys_gpl_txt <- tests/licensedcode/licensedcode_test_utils.py PASSED
tests/licensedcode/test_detection_datadriven1.py::TestLicenseDataDriven::test_detection_licenses_github_keys_lgpl_2_1_txt <- tests/licensedcode/licensedcode_test_utils.py PASSED
tests/licensedcode/test_detection_datadriven1.py::TestLicenseDataDriven::test_detection_licenses_github_keys_lgpl_3_0_txt <- tests/licensedcode/licensedcode_test_utils.py PASSED
tests/licensedcode/test_detection_datadriven1.py::TestLicenseDataDriven::test_detection_licenses_github_keys_lgpl_txt <- tests/licensedcode/licensedcode_test_utils.py PASSED
tests/licensedcode/test_detection_datadriven1.py::TestLicenseDataDriven::test_detection_licenses_github_keys_lppl_1_3c_txt <- tests/licensedcode/licensedcode_test_utils.py PASSED
tests/licensedcode/test_detection_datadriven1.py::TestLicenseDataDriven::test_detection_licenses_github_keys_mpl_2_0_txt <- tests/licensedcode/licensedcode_test_utils.py PASSED
tests/licensedcode/test_detection_datadriven1.py::TestLicenseDataDriven::test_detection_licenses_github_keys_ms_pl_txt <- tests/licensedcode/licensedcode_test_utils.py PASSED
tests/licensedcode/test_detection_datadriven1.py::TestLicenseDataDriven::test_detection_licenses_github_keys_ncsa_txt <- tests/licensedcode/licensedcode_test_utils.py PASSED
tests/licensedcode/test_detection_datadriven1.py::TestLicenseDataDriven::test_detection_licenses_github_keys_ofl_1_1_txt <- tests/licensedcode/licensedcode_test_utils.py PASSED
tests/licensedcode/test_detection_datadriven1.py::TestLicenseDataDriven::test_detection_licenses_github_keys_osl_3_0_txt <- tests/licensedcode/licensedcode_test_utils.py PASSED
tests/licensedcode/test_detection_datadriven1.py::TestLicenseDataDriven::test_detection_licenses_github_keys_postgresql_txt <- tests/licensedcode/licensedcode_test_utils.py PASSED
tests/licensedcode/test_detection_datadriven1.py::TestLicenseDataDriven::test_detection_licenses_github_keys_unlicense_txt <- tests/licensedcode/licensedcode_test_utils.py PASSED
tests/licensedcode/test_detection_datadriven1.py::TestLicenseDataDriven::test_detection_licenses_github_keys_wtfpl_txt <- tests/licensedcode/licensedcode_test_utils.py PASSED
tests/licensedcode/test_detection_datadriven1.py::TestLicenseDataDriven::test_detection_licenses_github_keys_zlib_txt <- tests/licensedcode/licensedcode_test_utils.py PASSED

======================================================== 30 passed, 1659 deselected in 21.11 seconds ========================================================
```
I guess it's ready to merge!

**Comment by pombredanne** [comment]
@sbs2001 thank you!

**Pull request merged**
