### PR TITLE
Correct id of summary and clues in help_template.html #892

### PR DESCRIPTION
**Pull request by techytushar**
PR for issue #892 . 
Signed-off-by: Tushar Mittal <chiragmittal.mittal@gmail.com>

### CODE REVIEW

**Comment by techytushar** [comment]
@pombredanne please review this, just a minor bug...

**Comment by pombredanne** [comment]
Thanks!
Are you sure and did you test if the tab navigation still works after these changes? I wonder if the # ijn this was not added on purpose by @jdaguil

**Comment by techytushar** [comment]
yes, after i removed the # it worked fine

**Comment by jdaguil** [comment]
@pombredanne this was an unintended bug. This fix LGTM.

**Comment by pombredanne** [comment]
Great! merging then.

**Pull request merged**
