### PR TITLE
Package Detection errors are not swallowed

### PR DESCRIPTION
**Pull request by fatemajawad**
Here , the error that were been swallowed and passed in the code , are no longer been swallowed but have been shown to the user

Fixes #0000

### Tasks

* [ ] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [ ] Commits are in uniquely-named feature branch and has no merge conflicts 📁

### CODE REVIEW

**Comment by pombredanne** [comment]
@fatemajawad Thank you for this... but your is not a solution I can contemplate.
I am not sure that `print(logger.error)` would do anything? `logger.error` is a function, so this would at best print on screen a function name? And in anycase we would not want to print things on screen. And we would need thorough autoamted testing.
https://github.com/nexB/scancode-toolkit/issues/2882 is a complex topic... so before jumping to a solution we need to discuss this there if this works for you.

**Comment by fatemajawad** [comment]
Sure sir I will look at the beginner problems and try my level best to
contribute to the organisation , sorry for the inconvenience caused by me

**Comment by pombredanne** [comment]
@fatemajawad you did not cause any inconvenience! and this is smart solution you have found, but this problem happens to much more complex than its looks on the surface :)

**Comment by fatemajawad** [comment]
Thank you!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Pull request closed without merging**
