### PR TITLE
Upgrade python package detection

### LINKED ISSUE #3753: SCTK: Detect pyproject.toml correctly
We should detect these. There are two kind:
- [ ] detect legacy poetry package in pyproject.toml that use a custom section. Some other tools like flit may use that
- [ ] detect modern pyproject.toml packages that use a unified section

See also:
- https://github.com/nexB/scancode-toolkit/issues/2109

### PR DESCRIPTION
**Pull request by AyanSinhaMahapatra**
- Add pyproject.toml support #3753
- Add poetry support #2109
- Improve python package assembly
- Add support for pip-inspect.deplock files https://github.com/nexB/scancode.io/issues/1262

Fixes #3753 

### Tasks

* [x] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [x] Commits are in uniquely-named feature branch and has no merge conflicts 📁
* [x] Updated documentation pages (if applicable)
* [x] Updated CHANGELOG.rst (if applicable)

### CODE REVIEW

**Review by keshav-space — APPROVED** [review]
Thanks @AyanSinhaMahapatra. LGTM!
For some reason macos-13 CIs are failing.

**Comment by AyanSinhaMahapatra** [comment]
We are failing tests in two places:
1. tests which require linux specific configuration it seems, like rpm. Maybe this is because we don't install them in macos specific cases? Like at https://github.com/nexB/scancode-toolkit/commit/c06705cec0f2fbd4245ced7d8b5d4906d9c1d28c @pombredanne need your input here. [Edit, this might actually be the heisenbug we often get, I forgot about that actually]
2. @keshav-space you added a `removesuffix()` method on a string but this is only available python 3.9+ it seems. See https://dev.azure.com/nexB/scancode-toolkit/_build/results?buildId=13829&view=logs&j=3dfa68ff-d50a-53ee-7b58-12d58c76da63&t=1b7369b2-e2fc-5889-2082-a49dded9cbd4&l=7020 and https://stackoverflow.com/questions/66683630/removesuffix-returns-error-str-object-has-no-attribute-removesuffix.  I'm not sure why this only fails in macos13 though. :thinking:

**Comment by keshav-space** [comment]
> 1. tests which require linux specific configuration it seems, like rpm. Maybe this is because we don't install them in macos specific cases?

Maybe we should skip these tests on macOS?


> 2\. @keshav-space you added a `removesuffix()` method on a string but this is only available python 3.9+ it seems. See https://dev.azure.com/nexB/scancode-toolkit/_build/results?buildId=13829&view=logs&j=3dfa68ff-d50a-53ee-7b58-12d58c76da63&t=1b7369b2-e2fc-5889-2082-a49dded9cbd4&l=7020 and https://stackoverflow.com/questions/66683630/removesuffix-returns-error-str-object-has-no-attribute-removesuffix.  I'm not sure why this only fails in macos13 though. 🤔

Ah, I missed that we're still supporting 3.8 :)

**Comment by AyanSinhaMahapatra** [comment]
Thanks @keshav-space , merging! This seems like the heisenbug, I will deal with this seperately if this persists.

**Pull request merged**
