### PR TITLE
Collect full stack trace for scan errors #784

### PR DESCRIPTION
**Pull request by yash-nisar**
Scan errors are now shown with a full stack trace for diagnosis
and no longer require the `--diag` option.

Signed-off-by: Yash Nisar <yash.nisar@somaiya.edu>

Closes https://github.com/nexB/scancode-toolkit/issues/784

### CODE REVIEW

**Comment by yash-nisar** [comment]
@pombredanne Please have a look when you're free 😉

**Comment by pombredanne** [comment]
@yash-nisar thanks ++ 
I may have troubles to merge this because of the changes that are about to be merged  from #885 
Can you see if this is possible?

**Comment by yash-nisar** [comment]
Oops, I'll have a look at the new plugin architecture. Thanks :)

**Comment by pombredanne** [comment]
I really appreciate all the effort you did put into this, but it may have gone stale or was superseded by my merge of #885 ... Can you see if the code that is now in develop makes sense? may be some extra tests could be added based on your work in this PR?

**Comment by yash-nisar** [comment]
Sure, I'll check it out and let you know. I appreciate the review. :smile:

**Comment by yash-nisar** [comment]
@pombredanne This patch was superseded by your merge of https://github.com/nexB/scancode-toolkit/pull/885 and the code in develop makes perfect sense. A scan with errors will always include the full traceback and we've gotten rid of the `--diag` flag. The following test confirms this : 
```
def test_scan_with_errors_always_includes_full_traceback():
    test_file = test_env.get_test_loc('failing/patchelf.pdf')
    result_file = test_env.get_temp_file('test.json')
    args = ['--copyright', test_file, '--json', result_file]
    result = run_scan_click(args, expected_rc=1)
    assert 'Some files failed to scan' in result.output
    assert 'patchelf.pdf' in result.output
    result_json = json.loads(open(result_file).read())
    expected = 'error: unpack requires a string argument of length 8'
    assert expected in result_json['files'][0]['scan_errors'][-1]
    assert result_json['files'][0]['scan_errors'][0].startswith('ERROR: for scanner: copyrights')
```

**Comment by yash-nisar** [comment]
@pombredanne Feel free to close this :)

**Comment by pombredanne** [comment]
OK closing! thanks again and sorry for having you waste cycles on this

**Pull request closed without merging**
