### PR TITLE
Support shortcut flags for cli

### LINKED ISSUE #2949: Support shortcut flags
## Short Description

It's annoying while typing `--about`, `--quiet`, `--verbose`, `--version` ... all the time.

It will be easier if the software supports shortcut flags

## Possible Labels

- new feature

## Select Category

-  [ ] Enhancement

## **Describe the Update**

Add support for shortcut flags to make CLI usage

## **How This Feature will help you/your organization**
It's will make CLI usage more efficient

## **Possible Solution/Implementation Details**

support flags like
```
-A    for about 
-q    for quietness
-V    for version of scancode-toolkit
-v    for verbose output
```

Fixed by #2951

### PR DESCRIPTION
**Pull request by lf32**
Supports
```
-A about
-q quiet
-v verbose
-V Version
```
shortcut flags

Fixes #2949

### CODE REVIEW

**Comment by lf32** [comment]
donot merge!

**Review by pombredanne — CHANGES_REQUESTED** [review]
These are all making sense! Thanks. Do you mind to also keep some test that uses the long form version?
And also add you name to the AUTHORs and update the changelog ?
Thanks!

**Comment by lf32** [comment]
> Do you mind to also keep some test that uses the long form version?

There are many tests which use long form version, I've altered only some of them to test for short flags but now I have added few more changes to other functions. The tests will now use both short form and long form versions
Thanks!

**Comment by lf32** [comment]
Is everything ok with this?

**Review by pombredanne — APPROVED** [review]
LGTM ! thanks

**Pull request merged**
