### PR TITLE
Added the NYSL License and rules files.

### PR DESCRIPTION
**Pull request by techytushar**
PR for the issue #400

### CODE REVIEW

**Comment by techytushar** [comment]
@pombredanne @RajuKoushik can you please tell what did i do wrong, why the checks have failed?

**Comment by pombredanne** [comment]
Thank you! Let me review this

**Comment by pombredanne** [comment]
Couple things
1. the commit subject line and message style: use imperative style for title, add your sign-off and the ticket number at the end of the subject line
2. we need a test for this too
3. I cannot merge this yet because we cannot support non-english licenses right away as this introduces too much bias in detection. So it will take a while to merge, but it will eventually

**Comment by pombredanne** [comment]
@techytushar why did you close this? You could just update this and I need it open and around so we can merge soon after I add support for international/non english licenses

**Comment by techytushar** [comment]
@pombredanne  I am really sorry for this. While squashing the commits together I did something wrong with the rebasing, so i had to delete that branch and create a new one. This won't happen in future :)

**Comment by pombredanne** [comment]
no need to be sorry, that not a problem: learning git is a process :P

**Comment by techytushar** [comment]
😄

**Pull request closed without merging**
