### PR TITLE
Add hippocratic license #1739

### PR DESCRIPTION
**Pull request by sbs2001**
Addreses #1739. Please review, and give feedback. 

If a rule is to be added for this license, I would like to work on it.

### CODE REVIEW

**Comment by sbs2001** [comment]
I can't clone the  repo locally (network issue) today. I will make the signoff changes as soon as possible(tomorrow atmost). 

By the way why are the builds failing?. The logs are not too helpful either.

**Comment by pombredanne** [comment]
> I can't clone the repo locally (network issue) today. I will make the signoff changes as soon as possible(tomorrow atmost).

Anytime is good. Thanks. So a small nit picking: we like to use an imperative style in our commit message titles, like if you are giving an order to the codebase to update itself. This also applies to the PR title. So I am updating from
` Added hippocratic license` to `Add hippocratic license #1739` 


>By the way why are the builds failing?. The logs are not too helpful either.

Let me see...

**Comment by pombredanne** [comment]
1. the first error is the lack of a signed-off-by in you commit messages (e.g. a "DCO" signoff) in https://github.com/nexB/scancode-toolkit/pull/1776/checks?check_run_id=266520891

2. another error is https://travis-ci.org/nexB/scancode-toolkit/jobs/599984043#L4350

```
__________________ TestLicense.test_validate_license_library ___________________
[gw0] linux2 -- Python 2.7.15 /home/travis/build/nexB/scancode-toolkit/bin/python
self = <test_models.TestLicense testMethod=test_validate_license_library>
    def test_validate_license_library(self):
        errors, warnings, infos = models.License.validate(
            cache.get_licenses_db(), verbose=True)
>       assert {} == errors
E       AssertionError: assert {} == {'hipporcratic-1.1': ['Unkno...vailable\nUnstated License']}
E         Right contains 1 more item:
E         {'hipporcratic-1.1': [u'Unknown license category: proprietary.\nUse one of these valid categories:\nCommercial\nCopyleft\nCopyleft Limited\nFree Restricted\nPatent License\nPermissive\nProprietary Free\nPublic Domain\nSource-available\nUnstated License']}
E         Full diff:
E         - {}
E         + {'hipporcratic-1.1': [u'Unknown license category: proprietary.\nUse one of these valid categories:\nCommercial\nCopyleft\nCopyleft Limited\nFree Restricted\nPatent License\nPermissive\nProprietary Free\nPublic Domain\nSource-available\nUnstated License']}
tests/licensedcode/test_models.py:131: AssertionError
```

or with a pretty presentation:
```
Unknown license category: proprietary.
Use one of these valid categories:
Commercial
Copyleft
Copyleft Limited
Free Restricted
Patent License
Permissive
Proprietary Free
Public Domain
Source-available
Unstated License
```


This measn that you need to use `Proprietary Free` and not `proprietary` as a license `category:`

**Comment by pombredanne** [comment]
Thank you for the updates. We are almost there... 
There is a small typo in your commit messages though: `hipporcratic` instaed of `hippocratic`

Do you mind to squash these commits and use use this message:
```
Add new hippocratic license  #1739

Signed-off-by: Shivam Sandbhor <shivam.sandbhor@gmail.com>
```

and then force push to your branch?
(Otherwise I can handle the squash if you do not feel comfortable with this)

**Comment by sbs2001** [comment]
@pombredanne  Thank you for pointing out the errors. This is been quite a  'git-exercise' for me(I really need to level-up my git skills). Hope you don't mind the ugly commit log. I guess we are finished. If you have some easy issues, do tell me they really aid in understanding the codebase.

**Comment by pombredanne** [comment]
@sbs2001 I will squash all this. May I also suggest that you try using the command line for Git? that's more work at first but it pays in the long run!
Thank you again!

**Comment by pombredanne** [comment]
This has been squashed and merged in #1779 and will soon land in the `develop`branch. Thanks!

**Pull request closed without merging**
