### PR TITLE
Improve copryight data stucture consistency #2350

### LINKED ISSUE #2350: Copyright and URLs data structure: Data structure inconsistency in results
### Description

`copyrights`, `holders`, `authors` use the `value` key where `urls` and `emails` use `url` and `email` as keys.

```
'urls': [{'url': 'http://pypi.python.org/pypi/python-cjson/1.0.5', 'end_line': 57, 'start_line': 57}]
'copyrights': [{'value': 'Copyright (c) 2009, by the authors', 'end_line': 4, 'start_line': 3}]
```

### PR DESCRIPTION
**Pull request by akugarg**
Signed-off-by: Akanksha Garg akanksha.garg2k@gmail.com
Fixes #2350

### Tasks

* [x] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [x] Commits are in uniquely-named feature branch and has no merge conflicts 📁

### CODE REVIEW

**Comment by TG1999** [comment]
Hi @akugarg your please sign off your commit, and try to write commit message in assertive manner for example instead of writing "Inconsistency Removed" write "Remove Inconsistency", and please try to squash your commits.

**Comment by akugarg** [comment]
Hey! @TG1999 
Sure!
I thought I will squash my commits in one go, once I am done with all changes since some of the checks were not yet succesfull :(.

**Comment by akugarg** [comment]
@pombredanne @majurg  @tdruez 
Can you please review this?

**Review by pombredanne — CHANGES_REQUESTED** [review]
@akugarg Thanks this is looking great!
This is a big API change so here is what I suggest:
1. let's make sure that the tests pass... this is mostly there and there are only a few failures left to handle: https://dev.azure.com/nexB/scancode-toolkit/_build/results?buildId=3033&view=logs&j=542f7780-35ea-5d32-9d04-17790cc67ad7&t=7089d4f4-8f65-5e5b-114f-497222ae4208

        =========================== short test summary info ============================
        FAILED tests/summarycode/test_summarizer.py::TestScanSummary::test_copyright_summary_base
        FAILED tests/summarycode/test_summarizer.py::TestScanSummary::test_copyright_summary_with_details
        FAILED tests/summarycode/test_summarizer.py::TestScanSummary::test_copyright_summary_with_details_plain_json
        FAILED tests/summarycode/test_summarizer.py::TestScanSummary::test_copyright_summary_does_not_crash
        FAILED tests/summarycode/test_summarizer.py::TestScanSummary::test_full_summary_base
        FAILED tests/summarycode/test_summarizer.py::TestScanSummary::test_full_summary_with_details
        FAILED tests/summarycode/test_summarizer.py::TestScanSummary::test_copyright_summary_key_files
        FAILED tests/summarycode/test_summarizer.py::TestScanSummary::test_full_summary_key_files
        FAILED tests/summarycode/test_summarizer.py::TestScanSummary::test_full_summary_key_files_json_lines
        FAILED tests/summarycode/test_summarizer.py::TestScanSummary::test_full_summary_by_facet
        FAILED tests/summarycode/test_summarizer.py::TestScanSummary::test_end2end_summary_and_classify_works_with_empty_dir_and_empty_values
        FAILED tests/formattedcode/test_output_templated.py::test_scan_html_output_does_not_truncate_copyright_html


2. beyond this there is a need to update the documentation and CHANGELOG 
3. I would want to make sure we give plenty of heads up to key adopters of ScanCode OR may be we could have a flag to keep the legacy behaviour?

**Comment by pombredanne** [comment]
gentle ping

**Comment by akugarg** [comment]
@pombredanne Sorry for the late reply.
I tried to look into all the mentioned files highlighted in the error but I was not able to detect from where 'value' is getting generated due to which my expected output is not matching and tests are failing.
Can you please explain a little more on this ,like how I can track that file ?

**Comment by pombredanne** [comment]
> I tried to look into all the mentioned files highlighted in the error but I was not able to detect from where 'value' is getting generated due to which my expected output is not matching and tests are failing.
> Can you please explain a little more on this ,like how I can track that file ?

That's weird indeed.

**Comment by pombredanne** [comment]
@akugarg here it is https://github.com/akugarg/scancode-toolkit/blob/Inconsistency-removed/src/summarycode/copyright_summary.py#L90

**Comment by akugarg** [comment]
> @akugarg here it is https://github.com/akugarg/scancode-toolkit/blob/Inconsistency-removed/src/summarycode/copyright_summary.py#L90

Thank you! Will try to solve it ASAP.

**Comment by pombredanne** [comment]
@akugarg Thanks for the updates! 

Do you mind to use proper descriptive commit messages?
"Inconsistency Removed"  and "updates" and "." could be made more descriptive I guess? :angel: 
We have some docs at https://aboutcode.readthedocs.io/en/latest/contributing/writing_good_commit_messages.html

**Comment by akugarg** [comment]
> @akugarg Thanks for the updates!
> 
> Do you mind to use proper descriptive commit messages?
> "Inconsistency Removed" and "updates" and "." could be made more descriptive I guess? 
> We have some docs at https://aboutcode.readthedocs.io/en/latest/contributing/writing_good_commit_messages.html

@pombredanne Thanks for your review.
Will definitely keep it in mind from the next time :p

**Comment by pombredanne** [comment]
You wrote:
> Will definitely keep it in mind from the next time 

I cannot merge a commit with a message that's just  ".". It won't happen ;)
Do you mind to amend your messages, then squash and rebase on the latest develop?
Thanks!

**Comment by pombredanne** [comment]
@akugarg Now that I have pushed a release, I am about to merge this: it would help me a lot if you could rebase on the latest develop branch and squash your commits in one.

**Comment by pombredanne** [comment]
@akugarg gentle ping... do you mind to rebase this?

**Comment by akugarg** [comment]
Hey! @pombredanne  Sry for the late reply! 
There is some mess created in this branch and my unable to get out of that. Would you mind if I close this and create a new PR for the same?

**Comment by pombredanne** [comment]
@akugarg sure thing. Please go ahead. 
This is ready to merge for me now other.

**Comment by pombredanne** [comment]
You can then force push here alright

**Comment by pombredanne** [comment]
@akugarg I merged and rebased this in https://github.com/nexB/scancode-toolkit/pull/2791 ... so we will continue there and I am closing this here!

**Pull request closed without merging**
