### PR TITLE
Improve dual AFPL/GPL license detection #2242

### LINKED ISSUE #2242: Incorrect license detection
### Description

The license detection is not correct when we scan the file `ghostscript-9.25~dfsg+1/contrib/gdevhl12.c` in the bundle `ghostscript_9.25~dfsg+1.orig.tar.xz`. The text below
```
108    Thanks to L. Peter Deutsch <ghost@aladdin.com> for making gdevdjet.c
109    and gdevdljm.[ch] available under a dual AFPL/GPL license.
```
is detected as
```
        "licenses": [
          {
            "key": "gpl-1.0-plus",
            "score": 11.0,
            "name": "GNU General Public License 1.0 or later",
            "short_name": "GPL 1.0 or later",
            "category": "Copyleft",
            "is_exception": false,
            "owner": "Free Software Foundation (FSF)",
            "homepage_url": "http://www.gnu.org/licenses/old-licenses/gpl-1.0-standalone.html",
            "text_url": "http://www.gnu.org/licenses/old-licenses/gpl-1.0-standalone.html",
            "reference_url": "https://enterprise.dejacode.com/urn/urn:dje:license:gpl-1.0-plus",
            "spdx_license_key": "GPL-1.0-or-later",
            "spdx_url": "https://spdx.org/licenses/GPL-1.0-or-later",
            "start_line": 2,
            "end_line": 2,
            "matched_rule": {
              "identifier": "gpl_200.RULE",
              "license_expression": "gpl-1.0-plus",
              "licenses": [
                "gpl-1.0-plus"
              ],
              "is_license_text": false,
              "is_license_notice": false,
              "is_license_reference": true,
              "is_license_tag": false,
              "matcher": "2-aho",
              "rule_length": 2,
              "matched_length": 2,
              "match_coverage": 100.0,
              "rule_relevance": 11
            },
            "matched_text": "   and gdevdljm.[ch] available under a dual AFPL/GPL license."
          }
        ],
```

The expected result is `AFPL or GPL`

### How To Reproduce

> scancode --copyright --license --info --license-diag --license-text --only-findings --is-license-text --strip-root --processes 4 --json-pp result.json 

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? (Windows/MacOS/Linux)
Linux
* What version of scancode-toolkit was used to generate the scan file?
3.2.0
* What installation method was used to install/run scancode? (pip/source download/other)
pip

### PR DESCRIPTION
**Pull request by lemoshi**
1. Add a rule to match the 'dual AFPL/GPL license'
2. Add a false-positive rule for a text in package 'ghostscript'.
   See more here: https://github.com/nexB/scancode-toolkit/issues/2242#issuecomment-698371970

Reported-by: @lemoshi
Signed-off-by: Lemon Shi <shir@vmware.com>

Fixes #2242

### Tasks

* [x] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [x] Commits are in uniquely-named feature branch and has no merge conflicts 📁

### CODE REVIEW

**Review by pombredanne — CHANGES_REQUESTED** [review]
Thank you++ :bow: 
there is this error to review:
```
E             Exception: 
E             Invalid rule YAML in directory: 'c:\\projects\\scancode-toolkit\\src\\licensedcode\\data\\rules'
E             While loading: file://c:\projects\scancode-toolkit\src\licensedcode\data\rules\afpl-9.0_or_gpl-1.0-plus_2.yml
E             Traceback (most recent call last):
E               File "c:\projects\scancode-toolkit\src\licensedcode\models.py", line 817, in __attrs_post_init__
E                 self.load()
E               File "c:\projects\scancode-toolkit\src\licensedcode\models.py", line 1083, in load
E                 raise Exception(msg.format(self))
E             Exception: Special License rule Rule(identifier='afpl-9.0_or_gpl-1.0-plus_2.RULE', license_expression='afpl-9.0 OR gpl-1.0-plus', minimum_coverage=0.0, only_known_words=False, relevance=100.0, length=0) is missing explanatory notes.
```

A false positive rule must have some notes explaining why this is a false positive so if you can add a note that would fix this,
I am not sure why the DCO bot complains otherwise.

**Comment by lemoshi** [comment]
Thanks Philippe. I have updated the commit accordingly. BTW, where did you see the error msg?
```
E             Exception: 
E             Invalid rule YAML in directory: 'c:\\projects\\scancode-toolkit\\src\\licensedcode\\data\\rules'
E             While loading: file://c:\projects\scancode-toolkit\src\licensedcode\data\rules\afpl-9.0_or_gpl-1.0-plus_2.yml
E             Traceback (most recent call last):
E               File "c:\projects\scancode-toolkit\src\licensedcode\models.py", line 817, in __attrs_post_init__
E                 self.load()
E               File "c:\projects\scancode-toolkit\src\licensedcode\models.py", line 1083, in load
E                 raise Exception(msg.format(self))
E             Exception: Special License rule Rule(identifier='afpl-9.0_or_gpl-1.0-plus_2.RULE', license_expression='afpl-9.0 OR gpl-1.0-plus', minimum_coverage=0.0, only_known_words=False, relevance=100.0, length=0) is missing explanatory notes.
```

**Comment by pombredanne** [comment]
@lemoshi re:

> BTW, where did you see the error msg?

You can see in the list of "checks" here the red cross marks for the travis and azure builds
For instance https://travis-ci.org/github/nexB/scancode-toolkit/jobs/731929125#L1580


And sorry for giving you an incorrect field name... it should be named `notes` and not `note`... hence why this is still failing.

**Comment by lemoshi** [comment]
@pombredanne OK, I could find the error msg now. Thanks!

**Review by pombredanne — APPROVED** [review]
Looking great! thank you ++ :bow:

**Pull request merged**
