### PR TITLE
#408 Change license category from Attribution to Permissive

### PR DESCRIPTION
**Pull request by pombredanne**
* the category changes are:
  * category: "Attribution Restricted" changed to: "Free Restricted"
  * category: "Atribution" changed to: "Permissive"

Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>

### CODE REVIEW

**Comment by pombredanne** [comment]
The reason why the tests pass on Windows and not on Linux/Mac is because the py.test config skips `etc/scripts` but only on Windows... I will fix this and then the json2csv expectations can be fixed for Windows alright.

**Comment by pombredanne** [comment]
@JonoYang I rebased this branch and forced pushed.... You may need to do some manual cherry picking on your side. The new CI setup will show you early in the build if etc/scripts tests failed and how.

**Comment by pombredanne** [comment]
@chinyeungli @JonoYang The commit I added should fix all the remaining json2csv issues. @chinyeungli I think you had try to update the expected CSV files with LibreOffice or similar and it had damaged the dates to convert them to spreadsheet dates. A similar thing may have happened to license score... Hence the failures. I fixed the tests accordingly

**Comment by pombredanne** [comment]
The tests runs are looking good and on their way to all pass

**Comment by chinyeungli** [comment]
thanks

**Comment by pombredanne** [comment]
@chinyeungli Thank you!

**Pull request merged**
