### PR TITLE
Format extracted_license_statement as YAML

### PR DESCRIPTION
**Pull request by AyanSinhaMahapatra**
See https://github.com/nexB/scancode.io/pull/715#discussion_r1197493136 

### Tasks

* [x] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [x] Commits are in uniquely-named feature branch and has no merge conflicts 📁
* [x] Looked for possible updates in documentation and added updates if applicable
* [x] Updated CHANGELOG.rst

### CODE REVIEW

**Comment by AyanSinhaMahapatra** [comment]
@pombredanne this is ready to review! We can do a rc5 after this is merged.

Btw, this was already in the changelog from this commit: https://github.com/nexB/scancode-toolkit/commit/d264aec5321354011d5fb2dd6118747a6c57eede but it was not YAML yet

**Review by pombredanne — CHANGES_REQUESTED** [review]
Thanks! we still need a few mini tests IMHO for a YAML, JSON and JSON-line outputs in formattedcode where we would have a few packages with such statements. I suggest an old npm (with a mapping), a new npm (with a single string as an expression) a Maven and PyPI with classifiers and license to have sample of the multiple use cases.

**Review by pombredanne — APPROVED** [review]
LGTM, we can add other output tests later

**Comment by AyanSinhaMahapatra** [comment]
@pombredanne thanks, I've also added the tests. Merging!

**Pull request merged**
