### PR TITLE
Resolve various path issues with SPDX output

### PR DESCRIPTION
**Pull request by sschuberth**
This fixes two issues at once: By reusing the existing SHA1 from `info`, we can easily skip directories when writing SPDX file entries as for these the SHA1 is empty.

### CODE REVIEW

**Comment by pombredanne** [comment]
You should not fetch things from the cache. This is an internal stuff and is meant to change at any time. You should instead use a scan with `info`.

**Comment by sschuberth** [comment]
Maybe I'm misunderstanding you here, but I need this to work also for scans that did not get the `-i` option passed on the command line...

**Comment by pombredanne** [comment]
ok then is this case, you want to force returning `info` if an SPDX output has been selected. And FWIW, IMHO `info` should be part of the default in all cases. Let me paste a snippet that does this

**Comment by pombredanne** [comment]
```patch
diff --git a/src/scancode/cli.py b/src/scancode/cli.py
index dc9664b..e36c798 100644
--- a/src/scancode/cli.py
+++ b/src/scancode/cli.py
@@ -262,6 +262,10 @@
         license = True
         package = True
 
+    # hack to force collecting info for SPDX outputs
+    if format in ('spdx-tv', 'spdx-rdf',):
+        info = True
+
     scans_cache_class = get_scans_cache_class()
     try:
         files_count, results = scan(input_path=input,
```

**Comment by pombredanne** [comment]
And then you can get the`sha1` directly this way:
```patch
diff --git a/src/scancode/cli.py b/src/scancode/cli.py
index dc9664b..62d669e 100644
--- a/src/scancode/cli.py
+++ b/src/scancode/cli.py
@@ -646,8 +646,11 @@
 
         for file_data in scanned_files:
             file_entry = File(file_data['path'])
-            # FIXME: should we really compue the checcksum here rather than get it from the scan?
-            file_entry.chk_sum = Algorithm('SHA1', file_entry.calc_chksum())
+            # get the sha1 from scan, it is part of the info
+            file_sha1 = file_data.get('sha1')
+            if file_sha1:
+                # do not add a sha1 if not present (e.g. not in scan or for a directory) 
+                file_entry.chk_sum = Algorithm('SHA1', file_sha1)
             for file_license in file_data['licenses']:
                 spdx_id = file_license.get('spdx_license_key')
                 # TODO: we should create a "LicenseRef:xxx" identifier 
```

**Comment by pombredanne** [comment]
This would be much better than trying to get this from the cache which is not something that should be relied on or used for anything except caching.

**Comment by pombredanne** [comment]
To more explicit, I would rather not rely on implementations details of the cache for any collected scan data: this is a better separation of concerns. It does today use a sha1 from the scan and may not tomorrow. If you were to use the sha1 as used in the cache internal cooking, you are making your scan output dependent on the caching implementation details and this would soon break when we use plugins for formats.

**Comment by sschuberth** [comment]
Thanks. Let me try to clarify once more: Doing the "hack to force collecting info for SPDX outputs" does *not* cause any additional scans to be performed. As such this is not really "*collecting* info", but more like "*exposing* info" that was already collected internally. Is that correct?

**Comment by pombredanne** [comment]
You wrote:
> Doing the "hack to force collecting info for SPDX outputs" does not cause any additional scans to be performed. As such this is not really "collecting info", but more like "exposing info" that was already collected internally. Is that correct?

This is correct, the `info` is not part of the "scans" in https://github.com/nexB/scancode-toolkit/blob/4df6e424ed22b0b8dcc5203f4228cdab7d7bfab3/src/scancode/cli.py because it is always done as part of the internals of caching here: https://github.com/nexB/scancode-toolkit/blob/4df6e424ed22b0b8dcc5203f4228cdab7d7bfab3/src/scancode/cli.py#L465 and the collected info are only it is injected in the returned results if `info` was True here: https://github.com/nexB/scancode-toolkit/blob/4df6e424ed22b0b8dcc5203f4228cdab7d7bfab3/src/scancode/cli.py#L437 otherwise the cache does not return that data, even though if was always generated

**Comment by sschuberth** [comment]
Thanks, then I'm confident that this is not as bad a hack as I thought in the beginning, and I just removed the "[WIP]" from the title.

**Comment by sschuberth** [comment]
@pombredanne Does this look good to you now?

**Comment by pombredanne** [comment]
@sschuberth looks all good, yet do you think you could add one or a couple tests? I can do it otherwise.

**Comment by sschuberth** [comment]
I didn't forget about the tests and I agree we need some, but I first wanted to fix the stuff that I know to be broken. But on top of that I have to admit that due to my limited time it might take me a while to add these tests.

**Comment by pombredanne** [comment]
@sschuberth fair enough. Merged.!

**Pull request merged**
