### PR TITLE
[WIP] Added main_license field to license model

### PR DESCRIPTION
**Pull request by ened**
TODO:
- unit tests
- double check other licenses for missing `main_license` fields

### CODE REVIEW

**Comment by ened** [comment]
Function-wise, this is ready for review @pombredanne. Next stop is are the tests.

**Comment by pombredanne** [comment]
@ened I am still pondering this in relation to #126 
We have cases and these are common where an exception can apply to multiple licenses.
For instance, there is a common exception to the GPL for openssl . See https://github.com/nexB/scancode-toolkit/blob/86283e1f0e114397dd030f4bf57067c2c47a8cdb/src/licensedcode/data/licenses/gpl-2.0-openssl.LICENSE
It is wrongly keyed after the GPL 2.0 but it applies to any GPL version.
There is a new batch of exceptions that is arriving from SPDX too, soon.
I want to make sure we come with the correct approach before adding a new attribute.

**Comment by pombredanne** [comment]
So as we are adding support for license expressions, the "main" or primary license will be the first member of an expression. This should alleviate the need for a specific attribute and will be exposed as a computed property instead

**Comment by pombredanne** [comment]
FYI, I pushed https://github.com/nexB/license-expression/ which is a library to parse and do some boolean analysis, comparison, normalization of license expressions. This is what I will use in ScanCode

**Comment by pombredanne** [comment]
@ened if you do not mind I would like to close this since the actual implementation that will land for this #126  will be closely related to #74 and  SPDX-like license expressions. I hope you do not feel bad about this: I will credit you in the related commits in all cases!  If you want to continue the discussion we can do it on #126

**Pull request closed without merging**
