### PR TITLE
#89 adding new test case for GPL 2.0

### PR DESCRIPTION
**Pull request by balusarakesh**
New test case for gpl-2.0 license is added.

### CODE REVIEW

**Comment by pombredanne** [comment]
@balusarakesh this is not passing the test yet?

**Comment by pombredanne** [comment]
@balusarakesh I would like to merge this but the tests are still failing

**Comment by balusarakesh** [comment]
@pombredanne  I couldn't figure out what's wrong with the NEWLY ADDED test cases. Please take a look and let me know what's wrong with the newly added tests.

**Comment by pombredanne** [comment]
ok, I will merge in and review

**Comment by pombredanne** [comment]
This has been merged into develop. Closing

**Pull request closed without merging**
