### PR TITLE
Return number of lines for a text file

### LINKED ISSUE #1350: Report the number of lines in a text file
Since scans (license and copyrights) typically return line ranges, it would be useful to return the number of lines if a file is a text file.

### PR DESCRIPTION
**Pull request by sritasngh**
Return the number of lines if a file is a text file.
Signed-off-by: Sarita Singh <saritasingh.0425@gmail.com>

Fixes #1350 

### Tasks

* [x] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [x] Commits are in uniquely-named feature branch and has no merge conflicts 📁

### CODE REVIEW

**Comment by sritasngh** [comment]
[input.txt](https://gist.github.com/itssingh/0cf79d53e651a0d1e132fff5dfd73825) 
`./scancode -lceui --json-pp - input.txt`
[output](https://gist.github.com/itssingh/461dd3f0d10a210308de3a8e97b50043#file-return_lines-json) Here is the number of lines https://gist.github.com/itssingh/461dd3f0d10a210308de3a8e97b50043#file-return_lines-json-L36.

**Comment by pratik0316** [comment]
@itssingh for the text file u provided shouldn't the total lines be 20?

**Comment by sritasngh** [comment]
> @itssingh for the text file u provided shouldn't the total lines be 20?

Actually I haven't counted empty lines. I can change this if needed.

**Comment by pratik0316** [comment]
@itssingh i believe we should account that

**Review by pombredanne — CHANGES_REQUESTED** [review]
@itssingh Thanks!
There is a some code that could potentially be stolen from https://github.com/nexB/scancode-plugins/blob/main/binary-analysis/scancode-compiledcode/src/sourcecode/metrics.py for this.
Overall I would prefer this to be a plugin and not something that goes by default in --info scans too.

**Comment by sritasngh** [comment]
@pombredanne I misunderstood when you mention to port [here](https://github.com/nexB/scancode-toolkit/issues/1350#issuecomment-809299158) sorry about that, Okay I'll create a new plugin. Thanks for review!

**Comment by pombredanne** [comment]
@itssingh gentle ping

**Comment by sritasngh** [comment]
> @itssingh gentle ping

Hey @pombredanne sorry for the delay, I have been selected as GSoC'21 student :) and I have started learning those stuff which I had mentioned in my proposal and community bonding so It's taking longer to resolve this issue.  It will take some more time as I'm working on this in parallel.

**Comment by pombredanne** [comment]
@itssingh gentle ping.

**Comment by pombredanne** [comment]
@itssingh I am closing this at this time. Please reopen if you feel like completing this!
Thanks!

**Pull request closed without merging**
