### PR TITLE
#296 Use gentoo licences as test data set

### LINKED ISSUE #296: Use gentoo licenses as a test data set
See https://gitweb.gentoo.org/repo/gentoo.git/tree/licenses

### PR DESCRIPTION
**Pull request by vikrant97**
Fixes #296 
Signed-off by: Vikrant Goyal vikrantgoyal97@gmail.com
@pombredanne please review this

### CODE REVIEW

**Comment by vikrant97** [comment]
@pombredanne I think I have done it in wrong way. Can u give me the link to how to add new licences?

**Comment by pombredanne** [comment]
Whoa! Thanks! I think that some of these may not be license but only license tests. Some may be rules for existings licenses, but not all would be licenses for sure.
See https://github.com/nexB/scancode-toolkit/wiki/How-to:-Add-new-license-rules-for-enhanced-detection

For a license the principle is the same, but you need a .yml and .LICENSE file pair for each license.

So see it all in action consider the for instance the files for the apache-1.0 licenses
- the reference license with its data and text file:
  - data file ass YAML: https://github.com/nexB/scancode-toolkit/blob/06cd94c127b82549382c61d3adec47e930923db1/src/licensedcode/data/licenses/apache-1.0.yml
  - license text: https://github.com/nexB/scancode-toolkit/blob/06cd94c127b82549382c61d3adec47e930923db1/src/licensedcode/data/licenses/apache-1.0.LICENSE

- example of an additional detection rule for this license:
  - https://github.com/nexB/scancode-toolkit/blob/06cd94c127b82549382c61d3adec47e930923db1/src/licensedcode/data/rules/apache-1.0.RULE
  - https://github.com/nexB/scancode-toolkit/blob/06cd94c127b82549382c61d3adec47e930923db1/src/licensedcode/data/rules/apache-1.0.yml

- other example of an additional rule for this license:
  - https://github.com/nexB/scancode-toolkit/blob/06cd94c127b82549382c61d3adec47e930923db1/src/licensedcode/data/rules/apache-1.0_1.RULE
  - https://github.com/nexB/scancode-toolkit/blob/06cd94c127b82549382c61d3adec47e930923db1/src/licensedcode/data/rules/apache-1.0_1.RULE

- and example of a detection test, here detecting two licenses at once: 
  - file to test : https://github.com/nexB/scancode-toolkit/blob/06cd94c127b82549382c61d3adec47e930923db1/tests/licensedcode/data/licenses/apache-1.0.txt
  - expected detection results for this file: https://github.com/nexB/scancode-toolkit/blob/06cd94c127b82549382c61d3adec47e930923db1/tests/licensedcode/data/licenses/apache-1.0.yml

I hope this helps.

**Comment by pombredanne** [comment]
See also the FAQ of course https://github.com/nexB/scancode-toolkit/wiki/FAQ
It can always be improved for sure.

**Comment by pombredanne** [comment]
And to put it all in context the internal design of the license detection is document here: https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/README.rst

**Comment by vikrant97** [comment]
Ok sir I will rework on this issue thanks for ur valuable review.

**Comment by pombredanne** [comment]
@vikrant97 is this something you still intend to work on and complete?

**Comment by pombredanne** [comment]
@vikrant97 any update? If not I might close this for now and you can reopen a new one later?

**Comment by pombredanne** [comment]
If I do not hear from you soon and you do not intend to work further on this I might just close this.
Please advise. Thanks!

**Comment by pombredanne** [comment]
@vikrant97 I assume that you have lost interest so I am closing for now. Please feel to reopen

**Pull request closed without merging**
