### PR TITLE
Add system packages support in the new packages model

### PR DESCRIPTION
**Pull request by AyanSinhaMahapatra**
### Tasks

* [x] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [x] Commits are in uniquely-named feature branch and has no merge conflicts 📁

### CODE REVIEW

**Comment by pombredanne** [comment]
@AyanSinhaMahapatra the latest jinja2 have some import changes https://github.com/sphinx-doc/sphinx/issues/10291 which makes some test fail.
IMHO we should:
1. use Python 3.9 for doc generation
2. bump all the doc deps.

**Comment by AyanSinhaMahapatra** [comment]
@pombredanne I bumped doc build tests to run on python3.9 here: https://github.com/nexB/scancode-toolkit/pull/2896

We don't use pinned requirements for doc builds anymore, using https://github.com/nexB/scancode-toolkit/blob/develop/setup.cfg#L133 instead. The above mentioned PR makes some changes and fixes the doc builds (updated skeleton with UI from @johnmhoran and --docs option in configure directly).

We can merge [this](https://github.com/nexB/scancode-toolkit/pull/2896) first in develop imho. (Not merging here because we need to amend and squash commits in this branch)

**Comment by pombredanne** [comment]
@AyanSinhaMahapatra  let's leave the tests/summarycode/ aside as this is is WIP from @JonoYang  in #2914

**Comment by AyanSinhaMahapatra** [comment]
> let's leave the tests/summarycode/

Yes, makes sense.

**Comment by pombredanne** [comment]
All green at last.....
Merging now!

**Pull request merged**
