### PR TITLE
Fix scancode-toolkit-mini and release prep v32.0.3 #3421

### LINKED ISSUE #3421: scancode-toolkit release is a scancode-toolkit-mini release
### Description

We don't have scancode-toolkit mini releases after v32.0.rc1: https://pypi.org/project/scancode-toolkit-mini/32.0.0rc1/#history
This is due to https://github.com/nexB/scancode-toolkit/commit/dd15f72984cd7f8b8766562b42e2073f4758881e#r116748649 in #3207 which went unnoticed.

As a result, we have only a scancode-toolkit pip release which is originally the scancode-toolkit-mini, and no actual scancode-toolkit release. Here in the release script both the wheels have same name, and so the later is only present in the release: https://github.com/nexB/scancode-toolkit/blob/develop/etc/release/scancode-create-pypi-wheel.sh

### PR DESCRIPTION
**Pull request by AyanSinhaMahapatra**
Fixes #3421 
Reference: https://github.com/nexB/skeleton/issues/75

### Tasks

* [x] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [x] Commits are in uniquely-named feature branch and has no merge conflicts 📁
* [x] Looked for possible updates in documentation and added updates if applicable
* [x] Updated CHANGELOG.rst

### CODE REVIEW

**Comment by AyanSinhaMahapatra** [comment]
@pombredanne @JonoYang all green, ready to review.
See also https://github.com/AyanSinhaMahapatra/scancode-toolkit/actions/runs/5191401446 where I've tested the release scripts. I've also tested this locally and check any artifact like here: https://github.com/AyanSinhaMahapatra/scancode-toolkit/suites/13413534948/artifacts/734815144, they now contain both the wheels for scancode-toolkit and scancode-toolkit-mini.

**Comment by pombredanne** [comment]
@AyanSinhaMahapatra I am not sure I get how this does fix the scancode-toolkit-mini build?

**Comment by AyanSinhaMahapatra** [comment]
https://github.com/nexB/scancode-toolkit/commit/dd15f72984cd7f8b8766562b42e2073f4758881e#r116748649 
@pombredanne see this ^ See also the description at https://github.com/nexB/scancode-toolkit/issues/3421#issue-1744140881
This commit: https://github.com/nexB/scancode-toolkit/pull/3422/commits/c205cee2e6d4f3e3e1642131cdf8b7e0bf1c3cb6 is the simple fix
 :stuck_out_tongue: I should have spotted this too in https://github.com/nexB/scancode-toolkit/pull/3207

**Review by pombredanne — APPROVED** [review]
LGTM :heart: Thanks!

**Comment by AyanSinhaMahapatra** [comment]
Thanks @pombredanne, merging!

**Pull request merged**
