### PR TITLE
Boostrap on Python 3 #295

### PR DESCRIPTION
**Pull request by pombredanne**
This PR:
- adds bootstrapping on Python with configure an related scripts. 
- allows to run Python 3 tests and run tests on Azure minimally using the new conftest plugin.

### CODE REVIEW

**Comment by Abhishek-Dev09** [comment]
@pombredanne : Is this only for python 2.7?

**Comment by pombredanne** [comment]
@Abhishek-Dev09 re:

> Is this azure only for python 2.7?

Of course not, but before we can enable anything on Python 3 we need to have the tests pass on Python 2.7 ... Azure is filled with peculiarities that require several adjustments.

**Comment by Abhishek-Dev09** [comment]
@pombredanne : Add these commit to this PR https://github.com/nexB/scancode-toolkit/pull/1534/commits/73ec89fa5000110b0a175ec633dd2fdfb0716819 , https://github.com/nexB/scancode-toolkit/pull/1534/commits/ce96b67991ece2bb48dcfd0bacdc1413191d6b6f , https://github.com/nexB/scancode-toolkit/pull/1534/commits/cbaf17d23f001ea3191d937c80ac97bdc009e142 , https://github.com/nexB/scancode-toolkit/pull/1534/commits/ff7612b0da18453ee9b7ff2f552b266043facbd6 , https://github.com/nexB/scancode-toolkit/commit/ff7612b0da18453ee9b7ff2f552b266043facbd6 , https://github.com/nexB/scancode-toolkit/pull/1534/commits/7b7946be65f09057a3e60d7731250c555b01b404 , https://github.com/nexB/scancode-toolkit/pull/1534/commits/150529eb8f6343018f2e224f17ee74cf6d96be9d , https://github.com/nexB/scancode-toolkit/pull/1534/commits/25c06791f597a0dd630b0e495a9aa6c009df5c57 .

**Comment by pombredanne** [comment]
@Abhishek-Dev09 re 

> Add these commit to this PR 73ec89f , ce96b67 , cbaf17d , ff7612b , 7b7946b , 150529e , and c8f7952

I would rather merge as is for now. and we can merge these afterwards

**Pull request merged**
