### PR TITLE
Fix incorrect license detection #2777

### LINKED ISSUE #2777: Incorrect license detection
### Description

```
This is the Debian GNU/Linux prepackaged version of GNU tar.  GNU
tar, heavily based on John Gilmore's public domain version of tar,
was originally written by Graham Todd.  It is now maintained by
Paul Eggert <eggert@twinsun.com>.

This package is maintained for Debian by Bdale Garbee <bdale@gag.com>, and
was built from the sources found at:

	ftp://ftp.gnu.org/gnu/tar/

More recently, I'm directly using the upstream source repository at 

	http://git.savannah.gnu.org/cgit/tar.git

GNU tar is 

   Copyright (C) 1988, 1992, 1993, 1994, 1995, 1996, 1997, 1999, 2000,
   2001, 2003, 2004, 2005, 2006, 2007 Free Software Foundation, Inc.

   This program is free software; you can redistribute it and/or modify it
   under the terms of the GNU General Public License as published by the
   Free Software Foundation; either version 3, or (at your option) any later
   version.

On Debian GNU/Linux systems, the complete text of the GNU General Public 
License version 3 can be found in /usr/share/common-licenses/GPL-3.

The Debian packaging is 

   Copyright (C) 2006, 2007 Bdale Garbee <bdale@gag.com>

   This program is free software; you can redistribute it and/or modify it
   under the terms of the GNU General Public License as published by the
   Free Software Foundation; either version 2, or (at your option) any later
   version.

On Debian GNU/Linux systems, the complete text of the GNU General Public 
License version 2 can be found in /usr/share/common-licenses/GPL-2.
```
The above notice from https://metadata.ftp-master.debian.org/changelogs//main/t/tar/tar_1.30+dfsg-6_copyright has `public-domain` detected
```
      "license_expressions": [
        "public-domain",
        "gpl-3.0-plus",
        "gpl-2.0-plus"
      ],
```

The `public-domain` is detected from `based on John Gilmore's public domain version of tar,`. Not sure can the tool be smart enough to tell `public-domain` is actually not the license for this package.

### PR DESCRIPTION
**Pull request by KevinJi22**
Adds a false positive rule for GNU tar. Also removes the public domain license as one of the expected outputs of the Debian slim copyright license test because the test has the same bug as the linked issue. Fixes #2777.

### Tasks

* [x] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [x] Commits are in uniquely-named feature branch and has no merge conflicts 📁

### CODE REVIEW

**Comment by KevinJi22** [comment]
@pombredanne the one test that fails after applying this change is the exact same bug reported in #2777. The expected output for the test is located on line 3 of `tests/packagedcode/data/debian/copyright/debian-slim-2021-04-07/usr/share/doc/tar/copyright-detailed.expected.yml`, and you can see that the test also expects a `public-domain` license.

Does this mean the test's expected output is incorrect? If it is, I can also fix the test. Or is #2777 actually not a bug?

**Comment by pombredanne** [comment]
@KevinJi22 This is not a clear cut... See  https://github.com/nexB/scancode-toolkit/issues/2777#issuecomment-1021923850

**Comment by pombredanne** [comment]
@KevinJi22 this is a bug alright as documented in https://github.com/nexB/scancode-toolkit/issues/2777#issuecomment-1025980464

**Comment by KevinJi22** [comment]
@pombredanne Yup, I fixed the bug in the second commit by removing the public domain license as one of the test's expected outputs.

**Review by pombredanne — APPROVED** [review]
the failure in https://github.com/nexB/scancode-toolkit/runs/5010476784?check_suite_focus=true  is not your making. Looking all good... Merging now!
Thank you ++

**Pull request merged**
