### PR TITLE
Fix-up the category of the 'ms-cla' license

### LINKED ISSUE #3317: The license category for `ms-cla` should be `cla`
The license is currently categorized as "patent license", whereas "cla" seems to be the better fit. See also https://github.com/nexB/scancode-licensedb/blob/ba55a604cb7b0bb614ae578d71a1be8fe37ba6d5/docs/ms-cla.json.

### PR DESCRIPTION
**Pull request by fviernau**
The license is a Contributor License Agreement, not a Patent License.

Fixes #3317.

### CODE REVIEW

**Comment by AyanSinhaMahapatra** [comment]
There is a paragraph:
```
b. Patent License. You grant Microsoft, and those who receive the Submission directly or indirectly from Microsoft, a perpetual, worldwide, non-exclusive, royalty-free, irrevocable license under Your patent claims that are necessarily infringed by the Submission or the combination of the Submission with the Project to which it was Submitted to make, have made, use, offer to sell, sell and import or otherwise dispose of the Submission alone or with the Project.
```

Which could be the reason why we mark this as a patent license.

@DennisClark is the above paragraph why we mark this as a `category: Patent License`?

**Comment by DennisClark** [comment]
@AyanSinhaMahapatra  Yes, but that  was because we created it before we created the CLA Category.  Now that we have the new Category, this license should definitely be assigned the CLA category.

**Comment by AyanSinhaMahapatra** [comment]
@DennisClark Thanks for the input.

**Review by AyanSinhaMahapatra — APPROVED** [review]
Thanks @fviernau, merging this!

**Pull request merged**
