### PR TITLE
#78 Added fixed vertical height for tree view

### PR DESCRIPTION
**Pull request by jdaguil**
For #78 I've added a fixed vertical height for scrolling in the tree view.

### CODE REVIEW

**Comment by pombredanne** [comment]
@jdaguil  Thanks for the PR!.... However I am not sure this is what should be done.
The height of the tree is not the problem , and it should IMHO match the height of the table based on the number of displayed rows.

However, the top level page bar, the whole tree itself and the header row of the table should be fixed to the top of the page, such that when you scroll, you scroll the table and not the tree not the headers.

The tree itself does not have to have a fixed size proper.

Having a fixed size constrained tree feels weird and small in most cases and I am not sure that it helps with navigation on pages with either very deep trees or many table elements displayed.

What's your take?

**Comment by jdaguil** [comment]
Thanks for the description @pombredanne! what you have suggested makes sense. From the ticket (#78), I misunderstood and thought the issue had to do with scrolling in the tree view.

**Comment by pombredanne** [comment]
@jdaguil The symptom is the scrolling in the tree view, but the underlying issue is that I think the tree could possibly be some iframe of sorts and things should be done such that you always have  visible on screen the tree bits and the table bits that you are looking at

**Comment by pombredanne** [comment]
@jdaguil this shows up as closed, because I merged, but I then reverted the commit... So this was not merged really

**Pull request merged**
