### PR TITLE
Add tests for SPDX and fix crash 

### PR DESCRIPTION
**Pull request by pombredanne**
This is for #633 and #474 and this adds the missing tests for #338
@abuhman you should give a trry to this branch for #633

### CODE REVIEW

**Comment by pombredanne** [comment]
@sschuberth this contains fixes to include the extracted license texts .... e.g. more or less about #588 but not yet full there. The logic is this:
If you used the `--license-text` option, then the texts are added to the SPDX RDF and TV formats
Otherwise for licenseref-like licenses, a link to the ScanCode .yml file for that license is added (this is because the extracted text for a licenseref is mandatory so we put something)

**Comment by sschuberth** [comment]
Thanks, these certainly are good changes. In our case, however, it probably doesn't help us as we've switched to using JSON output and convert that to our slightly customized flavor of SPDX tag / value in a post-processing step. I.e. we'd require the JSON output to already contain the license text as described in #504.

**Comment by pombredanne** [comment]
@sschuberth Thanks! And I will work out the rest of #504 for sure.
Out of curiosity, do you use the `spdx-tools` library then?

**Comment by sschuberth** [comment]
> Out of curiosity, do you use the `spdx-tools` library then?

No, because it does not allow us add custom tags, or comments to standards tags. Esp. the later is a feature we needed.

**Pull request merged**
