### PR TITLE
Add package_adder argument to assemble() #3034

### PR DESCRIPTION
**Pull request by JonoYang**
This PR adds a new argument, `package_adder`, to the `DatafileHandler.assemble()` method and to its subclassed variants as well. This is done to address the issues of running the different `assemble()` methods in a context outside of scancode-toolkit, see #3034 and https://github.com/nexB/scancode.io/issues/476.

### CODE REVIEW

**Review by pombredanne — APPROVED** [review]
Very nicely done! Clean and neat... one minor nitpicking: what about adding a test on one assemble function that passes a custom adder to validate the behaviour?
This would be nice... but this is good to merge as it is anyway.

**Comment by pombredanne** [comment]
We still need a CHANGELOG entry too.

**Comment by JonoYang** [comment]
@pombredanne Thanks for the review! I've added a new test where I run `get_package_and_deps` with a custom package adder and updated the changelog.

**Review by pombredanne — APPROVED** [review]
LGTM!

**Pull request merged**
