### PR TITLE
Add rule notes to license match results #1377

### PR DESCRIPTION
**Pull request by YashJipkate**
Added license rule notes to data returned with a license match.

### CODE REVIEW

**Comment by pombredanne** [comment]
@YashJipkate ping :) ... do not hesitate to ask for help on Gitter so we can help you there.

**Comment by YashJipkate** [comment]
@pombredanne thank you for the help. But I am in the middle of my exams so I can't attend to this right now. Though there were some problems faced in running the tests, I will elaborate on them as soon as I get some time.
Thanks again!

**Comment by pombredanne** [comment]
@YashJipkate ping... is this something you still want to work on and complete?

**Comment by YashJipkate** [comment]
Hi @pombredanne, sorry for the delay. I am facing a lot of troubles running the tests. The tests take a lot of time to run and consume all of my pc's memory. Also, I am getting this error `cannot import name models` after which it suggests to reconfigure or reinstall the repo. I did both and still not able to run the tests. They always fail. Do you have any idea regarding this?

**Pull request closed without merging**
