### PR TITLE
Add upstream CC-BY plain text license texts

### PR DESCRIPTION
**Pull request by sschuberth**
Please have a look at the individual commit messages for the details.

### CODE REVIEW

**Comment by pombredanne** [comment]
Thanks!
As you can see if you try to run a detection locally, the tests are failing massively because several of the plain texts already existed as rules before and now we have duplicates:

```
src/licensedcode/data/licenses/cc-by-nc-nd-3.0.LICENSE
src/licensedcode/data/rules/cc-by-nc-nd-3.0_2.RULE

src/licensedcode/data/licenses/cc-by-sa-3.0.LICENSE
src/licensedcode/data/rules/cc-by-sa-3.0_2.RULE

src/licensedcode/data/licenses/cc-by-3.0.LICENSE
src/licensedcode/data/rules/cc-by-3.0_2.RULE

src/licensedcode/data/licenses/cc0-1.0.LICENSE
src/licensedcode/data/rules/cc0-1.0_4.RULE

src/licensedcode/data/licenses/cc-by-nc-sa-3.0.LICENSE
src/licensedcode/data/rules/cc-by-nc-sa-3.0_2.RULE

src/licensedcode/data/licenses/cc-by-nd-3.0.LICENSE
src/licensedcode/data/rules/cc-by-nd-3.0_2.RULE

src/licensedcode/data/licenses/cc-by-nc-3.0.LICENSE
src/licensedcode/data/rules/cc-by-nc-3.0_2.RULE

src/licensedcode/data/licenses/cc-by-sa-4.0.LICENSE
src/licensedcode/data/rules/cc-by-sa-4.0_11.RULE

src/licensedcode/data/licenses/cc-by-4.0.LICENSE
src/licensedcode/data/rules/cc-by-4.0_1.RULE
```
what I suggest is that for each of these you take the old .LICENSE text before your change and update the corresponding duplicated .RULE file with that text: this way the dupes will go away AND the detection will still detect whatever was in the previous .LICENSE full text.

So as an example:
1. get the .LICENSE text of `src/licensedcode/data/licenses/cc-by-4.0.LICENSE` in develop
2. copy and paste its text in `src/licensedcode/data/rules/cc-by-4.0_1.RULE` in this branch

**Comment by sschuberth** [comment]
Sorry if this is a stupid question, but how do I know which rule file to copy to? Is it always the rule file whose base name ends with `_1`?

**Comment by sschuberth** [comment]
Nevermind, got it!

**Comment by pombredanne** [comment]
that's a proper question alright! In this list, each group of two lines in a pair of duplicated text files where the duplication has been introduced by your changes to the .LICENSE text.
 
Since we want to keep the new .LICENSE nicely formatted text you added alright in this `cc-plain-text` branch, then the old text (which would be the text in the .LICENSE file that's in the `develop` branch  e.g. `src/licensedcode/data/licenses/cc-by-nc-nd-3.0.LICENSE` for the first pair of dupes) needs to be copied and then pasted in this `cc-plain-text` branch as the context of the second file of the dupe pair, e.g. here `src/licensedcode/data/rules/cc-by-nc-nd-3.0_2.RULE` for the first pair in the list.
The only indication of which .RULE file name to update comes from the list, not from its name (such as a _1 suffix or else: there is no such meaning attached to names). 


```
src/licensedcode/data/licenses/cc-by-nc-nd-3.0.LICENSE
src/licensedcode/data/rules/cc-by-nc-nd-3.0_2.RULE

src/licensedcode/data/licenses/cc-by-sa-3.0.LICENSE
src/licensedcode/data/rules/cc-by-sa-3.0_2.RULE

src/licensedcode/data/licenses/cc-by-3.0.LICENSE
src/licensedcode/data/rules/cc-by-3.0_2.RULE

src/licensedcode/data/licenses/cc0-1.0.LICENSE
src/licensedcode/data/rules/cc0-1.0_4.RULE

src/licensedcode/data/licenses/cc-by-nc-sa-3.0.LICENSE
src/licensedcode/data/rules/cc-by-nc-sa-3.0_2.RULE

src/licensedcode/data/licenses/cc-by-nd-3.0.LICENSE
src/licensedcode/data/rules/cc-by-nd-3.0_2.RULE

src/licensedcode/data/licenses/cc-by-nc-3.0.LICENSE
src/licensedcode/data/rules/cc-by-nc-3.0_2.RULE

src/licensedcode/data/licenses/cc-by-sa-4.0.LICENSE
src/licensedcode/data/rules/cc-by-sa-4.0_11.RULE

src/licensedcode/data/licenses/cc-by-4.0.LICENSE
src/licensedcode/data/rules/cc-by-4.0_1.RULE
```

**Comment by pombredanne** [comment]
@sschuberth there is still one test failure when testing that tests/licensedcode/data/licenses/cc-by-nd-4.0.txt returns `cc-by-nd-4.0` ... and it fails and returns instead `cc-by-4.0` which is a big difference. IMHO the easiest is add a new rule  for it based on the former license text that was for cc-by-nd-4.0
https://github.com/nexB/scancode-toolkit/pull/1320/files#diff-859eceb7a3068eb35071fa46a5c31010

and of add a rule that matches the text in the failing test?

**Comment by sschuberth** [comment]
@pombredanne, done. At least I hope that 😆

**Comment by pombredanne** [comment]
a quick `py.test -vvs -k cc_by_nd` locally tells me that should be fine.

**Comment by pombredanne** [comment]
All green. Thanks!

**Pull request merged**
