### PR TITLE
ADDED: LLAMA-2-community.LICENSE.

### PR DESCRIPTION
**Pull request by xonx4l**
ISSUE-:#3463

ADDED: LLAMA-2-community.LICENSE.

Fixes-:#3463

### CODE REVIEW

**Review by pombredanne — CHANGES_REQUESTED** [review]
Thanks... there a few issues with this commit you would need to address:
1. the name is not all lowercase
2. the path "licenses " is incorrect as the dir has a trailing whitespace
3. the file is missing the frontmatter metadata
4. the commit is missing a DCO signoff
5. the tests are failing

**Comment by pombredanne** [comment]
Gentle ping

**Comment by pombredanne** [comment]
I am closing this as this has been added elsewhere https://github.com/nexB/scancode-toolkit/commit/8de1e90d1428547578f55cf50af0b3fa49699edc#diff-4f88aa34d34a3a903427def8c5333caca01a41f25d406e04b776473fb8bec2a7 ... this shows also what this would need to look like.

**Comment by AyanSinhaMahapatra** [comment]
@xonx4l Thanks++ for your contribution.
We added this elsewhere at https://github.com/nexB/scancode-toolkit/edit/develop/src/licensedcode/data/licenses/llama-2-license-2023.LICENSE and https://scancode-licensedb.aboutcode.org/llama-2-license-2023.html so closing this!

**Pull request closed without merging**
