### PR TITLE
Ensure CLI input is bytes on Linux #688

### PR DESCRIPTION
**Pull request by pombredanne**
* somehow this important change got lost in rebases and merges
 * add CLI test with express/serve-static test files
 * See #688

Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>

### CODE REVIEW

**Comment by sschuberth** [comment]
> somehow this important change got lost in rebases and merges

Just as a hint, as something similar occurred to me recently, too: Never use `git rebase -i` together with `-p`, as that might lead to [commits being dropped from the main line](https://git-scm.com/docs/git-rebase#_bugs).

**Comment by sschuberth** [comment]
With this merged, I'm still getting `UnicodeEncodeError`, though at a different location:

    XXX path u'test/fixtures/snow \udce2\udc98\udc83'
    Traceback (most recent call last):
      File "/workspace/tools/scancode/bin/scancode", line 11, in <module>
        load_entry_point('scancode-toolkit', 'console_scripts', 'scancode')()
      File "/workspace/tools/scancode/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
        return self.main(*args, **kwargs)
      File "/workspace/tools/scancode/src/scancode/utils.py", line 74, in main
        standalone_mode=standalone_mode, **extra)
      File "/workspace/tools/scancode/local/lib/python2.7/site-packages/click/core.py", line 697, in main
        rv = self.invoke(ctx)
      File "/workspace/tools/scancode/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/workspace/tools/scancode/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/workspace/tools/scancode/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
        return f(get_current_context(), *args, **kwargs)
      File "/workspace/tools/scancode/src/scancode/cli.py", line 486, in scancode
        pre_scan_plugins=pre_scan_plugins)
      File "/workspace/tools/scancode/src/scancode/cli.py", line 634, in scan
        result = scanned.next()
      File "/workspace/tools/scancode/local/lib/python2.7/site-packages/click/_termui_impl.py", line 257, in next
        return next(self.iter)
      File "/workspace/tools/scancode/src/scancode/cli.py", line 729, in _resource_logger
        file_logger(logfile_fd, rel_path)
      File "/workspace/tools/scancode/src/scancode/cache.py", line 219, in log_file_path
        path = path_to_bytes(path) + b'\n'
      File "/workspace/tools/scancode/src/commoncode/fileutils.py", line 232, in path_to_bytes
        return osb.fsencode(path)
      File "/workspace/tools/scancode/local/lib/python2.7/site-packages/backports/os.py", line 133, in fsencode
        return filename.encode(encoding, errors)
    UnicodeEncodeError: 'ascii' codec can't encode character u'\udce2' in position 19: ordinal not in range(128)

But as it fixes at least one occurrence, I guess this commit is good anyway.

**Comment by pombredanne** [comment]
BTW, Travis has some issue with the macOS builds atm: https://www.traviscistatus.com/incidents/4qylrqvy50gy

**Comment by pombredanne** [comment]
Ok I am merging this one.

**Pull request merged**
