### PR TITLE
Release smoke test

### PR DESCRIPTION
**Pull request by Abhishek-Dev09**

### CODE REVIEW

**Comment by pombredanne** [comment]
@Abhishek-Dev09 this is breaking all the Windows CI. Are you sure you know what needs to be done here? Also all your commits are missing a DCO signed-off-by

**Comment by Abhishek-Dev09** [comment]
> @Abhishek-Dev09 this is breaking all the Windows CI. Are you sure you know what needs to be done here? Also all your commits are missing a DCO signed-off-by

I think i need to write separate python program for this test that is built on native window command prompt.

**Comment by pombredanne** [comment]
that would not be a python program but a ps or bat... though using a Python script instead for a cross platform release script could work too. Are you finishing this PR or closing it for now?

**Comment by Abhishek-Dev09** [comment]
[untitled.txt](https://github.com/nexB/scancode-toolkit/files/2945753/untitled.txt)
Here is my syntax error,Can anyone help me to get rid of error?
I am not familiar with batch file.

**Comment by pombredanne** [comment]
@Abhishek-Dev09 if you are not familiar with Windows commands, it might be best not to try to fix this before you learn it. And if you have a bat/ps1/cmd file to submit for review... please commit this in the PR and do not attach it to the PR. Attachments are impossible to review or comment.

**Comment by pombredanne** [comment]
I am closing this now as this cannot really be merged.

**Pull request closed without merging**
