### PR TITLE
Verified Licenses for issue#1381

### PR DESCRIPTION
**Pull request by hamzam1997**
Licenses are verified. All licenses are detected correctly. JSON reports are included.

[nexb/scancode-toolkit#1381](https://github.com/nexB/scancode-toolkit/issues/1381)

### CODE REVIEW

**Comment by pombredanne** [comment]
@hamzam1997 thank you for verifying this. I am not sure what the files you want to add are bringing since they are just reports but not automated tests. May you wanted to attach them to the ticket instead and not commit them?
Alternatively I could accept unit tests for this (eventually breaking down the file under test in several small and focused test files) that would be added to the data-driven tests in https://github.com/nexB/scancode-toolkit/tree/develop/tests/licensedcode/data/licenses

**Comment by pombredanne** [comment]
?

**Comment by hamzam1997** [comment]
@pombredanne Hi! I apologize for late feedback. 
1. I committed the files to make sure you can access them easily, 
1. It will be very beneficial if you can explain and breakdown the process how should I go about this [issue #1381 ](https://github.com/nexB/scancode-toolkit/issues/1381)? I ran a test using help from the documentation provided [here](https://github.com/nexB/scancode-toolkit/wiki/How-To:-Run-a-scan) and then manually verified all the licenses included in the report

**Comment by pombredanne** [comment]
See https://github.com/nexB/scancode-toolkit/issues/296#issuecomment-284451265 for extra  details. I am clising in the meantime, because I cannot merge this as is.

**Pull request closed without merging**
