### PR TITLE
Fix Google Fuchsia license

### PR DESCRIPTION
**Pull request by tsteenbe**
Fix misspelling Fuschia -> Fuchsia and update URL

### CODE REVIEW

**Comment by tsteenbe** [comment]
@pombredanne  I just notice there is also a `other_urls:` field for .yml files. Instead of removing the original link to https://github.com/flutter/flutter/blob/master/PATENTS shall I moved it to `other_urls:` field?

So google-patent-license-fuchsia.yml becomes:

```
key: google-patent-license-fuchsia
short_name: Google Patent License for Fuchsia
name: Google Patent License for Fuchsia
category: Patent License
owner: Google
homepage_url: https://fuchsia.googlesource.com/fuchsia/+/refs/heads/master/PATENTS
faq_url: https://en.wikipedia.org/wiki/Google_Fuchsia
other_urls:
    - https://github.com/flutter/flutter/blob/master/PATENTS
```

**Comment by pombredanne** [comment]
Thank you ++ I important caveat though before I can merged: we cannot change a license key ever.
What we do instead is create a new one with the new key and mark the old one with `is_deprecated: yes` and add notes to it with  `notes: renamed to xxx` with the new license key ... this provides some guarantee of stability of license keys

**Comment by pombredanne** [comment]
> Instead of removing the original link to https://github.com/flutter/flutter/blob/master/PATENTS shall I moved it to other_urls: field?

yes, that works

**Comment by pombredanne** [comment]
@tsteenbe I applied the fixes to your branch directly as I want to merge this today.

**Pull request merged**
