### PR TITLE
configure command update for win 10

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
Fixes:

Error

### Tasks

* [x] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [x] Commits are in uniquely-named feature branch and has no merge conflicts 📁

### CODE REVIEW

**Comment by Siddhant-K-code** [comment]
@pombredanne please review!

**Comment by pombredanne** [comment]
@Siddhant-K-code Thanks for this, but "configure" is working fine on Windows for me. What's your configuration?

**Comment by Siddhant-K-code** [comment]
> @Siddhant-K-code Thanks for this, but "configure" is working fine on Windows for me. What's your configuration?

how should it run, its a file (script) , so for executing it we have to use that command only!!

**Comment by pombredanne** [comment]
Typing "configure" is enough. See https://github.com/nexB/scancode-toolkit/blob/d293bb9c178f170fa8c2b7909b8ad6d160a1191c/etc/ci/azure-win.yml#L35

So I do not think this is needed. I am closing then. Thank you for trying though!

**Pull request closed without merging**
