### PR TITLE
used argparser instead of raw processing sign off: seeni<seeni0424@gm…

### PR DESCRIPTION
**Pull request by Seenivasanseeni**
I am using argparser . The current code just reads command line arguments and then processing it. Using this library will greatly enhance readability and feature rich.

### CODE REVIEW

**Comment by pombredanne** [comment]
@Seenivasanseeni Thank you for this!
A couple things for your review:
1. I appreciate your efforts but the configure script is meant to have as few moving parts as possible and very few options if any. What do I gain to use argparse there? there is no plan to add more options here. And when designed `configure` was also running on Python 2.6 (and is eventually still used on 2.6) and there is no argparse builtin on 2.6. So based on that I am not inclined to use argparse at all.

2. please check out https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst and especially the Sign-off-by format for your commit messages... this must be exactly a DCO signoff.

If you have other ideas this is great and let's discuss them first on the chat channel.
Thank you again!

**Comment by QuLogic** [comment]
>     1. And when designed `configure` was also running on Python 2.6 (and is eventually still used on 2.6) and there is no argparse builtin on 2.6. So based on that I am not inclined to use argparse at all.

I don't care about this change too much in particular, but wasn't the result of #295 to change to Python 3 _only_ after scancode 3.x (which is out), so support of 2.6 is kind of irrelevant, isn't it?

**Comment by pombredanne** [comment]
@QuLogic True, 2.6 is kind of irrelevant (I mentioned it to provide some historical background) ... but so is making a change to use argparse in this specific context where we have so little argument parsing involved AND this is a script that is used likely many thousand++ times  as every new install of scancode runs this script. This is NOT an area I want to change likely and introduce a new dependency. argparse even if standard lib IS a new dependency.

Also as explained in https://github.com/nexB/scancode-toolkit/issues/295#issuecomment-469076254 by @dankegel the port from 2 to 3 has to be a gradual process where small, incremental and consistent changes that work on both Python versions are merged on a regular basis. I will NOT accept some kind of massive PR that upgrades for 2 to 3 at once, that would be a complete waste of time. 
Also note that work on #295 is not even started yet. At least I have not seen any code yet.

I hope this makes sense :smile_cat:

**Comment by dankegel** [comment]
Configure scripts are used while bootstrapping, as it were, and it may be wise to do raw processing rather than pull in libraries.

What problem are you trying to solve?  Try filing an issue for that first.  If you're working on #295, 
it might be better to ignore the configure script and thirdparty for now, and focus on a local editable pip install as I described in my long comment there.

**Pull request closed without merging**
