### PR TITLE
Improve debian license detection #2390 

### PR DESCRIPTION
**Pull request by pombredanne**
This PR is to improve how we handle Debian license detection in copyright files for #2390

### CODE REVIEW

**Comment by pombredanne** [comment]
The overall approach to properly detect licenses in copyright files is this:

- we have a specific process for files that are no machine-readable, treating them mostly as plain text, and using some heuristics to break them in chunks as needed

- for machine-readable files, they are parsed in paragraphs and processed this way:
1. handle license paragraphs first:
a. detect the license in the text/body and/or notes/comments 
b. parse the License:tag and determine if this is a common license or not
c. compare, reconcile and validate a. and b. consistency and eventually create and store a new license "symbol" reference from b. using the detected license in a.

2. handle the files paragraphs and the header paragraph second, using the list of new license symbols created in 1. 
a. detect the license in the text/body and/or notes/comments 
b. parse the License:tag as a license expression using the common license symbols and the symbols found in 1.
c. compare, reconcile and validate a. and b. consistency and issues

3. report results as a list of license matches

**Comment by AyanSinhaMahapatra** [comment]
@pombredanne This ^ commit adding a new way of Unknown LicenseMatch makes mostly all the tests that was failing before, apart from some seemingly unrelated ones like this one:
```
_______________________________ TestPypiArchive.test_parse_with_wheelfile ________________________________

self = <test_pypi.TestPypiArchive testMethod=test_parse_with_wheelfile>

    def test_parse_with_wheelfile(self):
        test_file = self.get_test_loc('pypi/archive/atomicwrites-1.2.1-py2.py3-none-any.whl')
>       package = pypi.parse(test_file)

tests/packagedcode/test_pypi.py:97:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
src/packagedcode/pypi.py:134: in parse
    package = parser(location)
src/packagedcode/pypi.py:197: in parse_archive
    return parse_metadata(metafile)
src/packagedcode/pypi.py:169: in parse_metadata
    meta = dist.metadata
/usr/lib/python3.8/importlib/metadata.py:224: in metadata
    self.read_text('METADATA')
/usr/lib/python3.8/importlib/metadata.py:491: in read_text
    return self._path.joinpath(filename).read_text(encoding='utf-8')
/usr/lib/python3.8/zipfile.py:2329: in read_text
    with self.open() as strm:
/usr/lib/python3.8/zipfile.py:1530: in open
    fheader = zef_file.read(sizeFileHeader)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <zipfile._SharedFile object at 0x7fd7b9945dc0>, n = 30

    def read(self, n=-1):
        with self._lock:
            if self._writing():
                raise ValueError("Can't read from the ZIP file while there "
                        "is an open writing handle on it. "
                        "Close the writing handle before trying to read.")
>           self._file.seek(self._pos)
E           ValueError: seek of closed file

/usr/lib/python3.8/zipfile.py:763: ValueError
```
Would you take a look?

**Comment by AyanSinhaMahapatra** [comment]
All green!

**Comment by pombredanne** [comment]
All green at last! merging now.
@AyanSinhaMahapatra thanks!

**Pull request merged**
