### PR TITLE
Do not print unwanted log warning message #1691

### LINKED ISSUE #1691: scancode with --summary throws warnings about missing logger handlers
### Description
Please leave a brief discription of the bug or feature request:

When running scancode with the --summary option I get warnings:

    No handlers could be found for logger "bs4.dammit"

Scancode was run as follows:

    $ ./scancode --full-root -l --license-text -c -e -u -n 8 --summary --json-pp=/tmp/output.json2 /tmp/busybox-1.28.0/

### System configuration
For bug reports, it really helps us to know:
* What OS are you running on? (Windows/MacOS/Linux) - Fedora 30
* What version of scancode-toolkit was used to generate the scan file? - develop branch, commit 483e47a69e24a0b9ac08f0861ce63dbb7be457f9
* What installation method was used to install/run scancode? (pip/source download/other) - source download

### PR DESCRIPTION
**Pull request by Iamshankhadeep**
fixes #1691

### CODE REVIEW

**Comment by Iamshankhadeep** [comment]
@pombredanne  Is the commit message okay now?  I changed it to what you said and also left an empty line before the `import`.

**Comment by Iamshankhadeep** [comment]
can you help me figure out by saying how can I watch from py.test that what has been printed on the screen while I run scancode?

**Comment by pombredanne** [comment]
> can you help me figure out by saying how can I watch from py.test that what has been printed on the screen while I run scancode?

1. commit a test file in a sub dir of https://github.com/nexB/scancode-toolkit/tree/develop/tests/scancode/data  ... it should be the file at https://github.com/nexB/scancode-toolkit/issues/1691#issuecomment-542219152

2. add a test similar to this test https://github.com/nexB/scancode-toolkit/blob/3bbc9e0a2319cacea0ff7b7a97d432136acc4fdf/tests/scancode/test_cli.py#L101

2.1 you want to run a scan for `--copyright` on the test file above
2.2 you want to test that the result.output does not contain neither `"No handlers could be found for logger"` nor `"Some characters could not be decoded"` ... and to be on the safe side, make sure your test fails correctly if your patch is not applied.

**Comment by pombredanne** [comment]
@Iamshankhadeep I am going to merge this as-is for now as we need it... Would you mind to submit a new PR with a test? that would be great!
Thank you again.

**Comment by pombredanne** [comment]
@Iamshankhadeep 

re:

>  I am working on the test, I need 2-3 hours for that.

no rush! thank you ++

**Pull request merged**
