### PR TITLE
Yield multiple packages #1771

### PR DESCRIPTION
**Pull request by JonoYang**
This PR allows the `Package` class' `recognize` method to return multiple Package objects for a single manifest, if more than one Package was detected.

### CODE REVIEW

**Comment by pombredanne** [comment]
@JonoYang is this now obsolete?

**Comment by JonoYang** [comment]
@pombredanne What do you mean by obsolete?

**Comment by pombredanne** [comment]
@JonoYang my bad... I mixed it up with #1788

**Comment by pombredanne** [comment]
@JonoYang looking all :green_apple:  now... merging! thank you++

**Pull request merged**
