### PR TITLE
1220 lockfile support

### PR DESCRIPTION
**Pull request by JonoYang**
Related to #1850 and #1852, this PR adds more lock file parsers to ScanCode.

### CODE REVIEW

**Comment by pombredanne** [comment]
Thanks... Here are a couple sources of yarn lock test files to consider:
- https://github.com/imsnif/synp/tree/master/test/fixtures (also interesting because it's description is `Convert yarn.lock to package-lock.json and vice versa`
- https://github.com/yarnpkg/yarn/blob/master/__tests__/fixtures

**Comment by JonoYang** [comment]
@pombredanne Thanks for the links. This test looks interesting: https://github.com/imsnif/synp/blob/master/test/fixtures/file-deps-yarn/yarn.lock

Should ScanCode consider handling dependencies where the requirement is pointing to a file?

**Comment by pombredanne** [comment]
> Should ScanCode consider handling dependencies where the requirement is pointing to a file?

Not sure. What's your take?

**Comment by JonoYang** [comment]
It would be useful to know that this is a dependency being used, but this is also the first time I seen something like this in a project, so I don't think this is that common.

**Comment by pombredanne** [comment]
All good, but we need to use smaller test files... the yarn.lock sample  you have for tests is a tad big.
Merging though... you can fix it later

**Pull request merged**
