### PR TITLE
#535 Remove '/code' from expected output

### PR DESCRIPTION
**Pull request by agneet42**
Removed '/code' from expected output in test_json2csv.py.

### CODE REVIEW

**Comment by agneet42** [comment]
@JonoYang @pombredanne , please review the changes made in test_json2csv.py as requested by @JonoYang

**Comment by JonoYang** [comment]
Thanks for the update! Looking at Travis CI, a few tests are failing because the test data files also need to be updated. `test_json2csv.py` uses test data files from [here](https://github.com/agneet42/scancode-toolkit/tree/3190b44ca3e035d374d0f67223f0161cf40da95a/etc/scripts/testdata/json2csv) and the path values still have `/code` prepended to them.

You should remove `/code` from the path values of these files:
- `full.csv`
- `full.json-expected`
- `minimal.csv`
- `minimal.json-expected`
- `package_license_value_null.json-expected`

**Comment by agneet42** [comment]
@JonoYang, do I make all the file changes under this PR itself?

**Comment by JonoYang** [comment]
@agneet42 Yes. I think you can add those changes to this PR.

**Comment by agneet42** [comment]
@JonoYang, please review the changes.

**Comment by pombredanne** [comment]
Other comments: 

Did you check https://github.com/nexB/aboutcode/wiki/Writing-good-commit-messages ?
We would prefer "Remove" to "Removed"

Also we do not need 6 commits for this but one squashed commit. And you need to add a "Signed-off-by" to your commit

**Comment by agneet42** [comment]
@pombredanne , I'll do the necessary changes.

**Comment by pombredanne** [comment]
@agneet42 I am not sure why you closed this rather than update your branch?

**Comment by agneet42** [comment]
I'm merging the changes of this patch into the the previous patch , i.e #524, hence.

**Pull request closed without merging**
