### PR TITLE
#322 Improved data structure using files instead of results

### PR DESCRIPTION
**Pull request by pombredanne**
This is for #322
 * also flatten file infos as file object attributes
 * update the json, html and html-app outputs and their tests

@jdaguil @sesser please review.

Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>

### CODE REVIEW

**Comment by sesser** [comment]
Say wha? Don't believe I have any say in this project ;)

**Comment by pombredanne** [comment]
@sesser sorry, @majurg is Steven Esser and goes by @sesser elsewhere :) I made a typo!

**Comment by sesser** [comment]
ARRRRRRGH! Another Esser! :D I get emails for other S. Esser's as well. 

No worries... carry on :)

**Comment by majurg** [comment]
@pombredanne it looks good, I will have to spend some time playing with the new results and see how they impact things on the branches on my side

**Comment by pombredanne** [comment]
@sesser All sessers are fine people in my book. And your instaphp looks great!
Sorry again for the noise

**Comment by jdaguil** [comment]
@pombredanne lgtm!

**Pull request merged**
