### PR TITLE
Alternate pdf handling

### PR DESCRIPTION
**Pull request by pombredanne**
This is a fix for #740 
The fix consists of

1. switching to pdfminer.six maintained by @goulu which is actually a maintained version of pdfminder that upstream seems to have abandoned otherwise.... Thanks to  @goulu and team !

2. use io.StringIO instead of plain StringIO to better cope with unicode issues

### CODE REVIEW

**Comment by pombredanne** [comment]
@sschuberth yes! good catch

**Comment by sschuberth** [comment]
@pombredanne, any objections to merge this?

**Comment by pombredanne** [comment]
@sschuberth no objections, I just need to add the pre-built native wheels for pycyptodome on Linux and macOS.
I kicked a build at  https://github.com/pombreda/thirdparty-manylinux/ and https://github.com/pombreda/thirdparty

These should show up shortly at http://dl.bintray.com/pombreda/thirdparty/

**Comment by pombredanne** [comment]
All set... Merging! thanks again for the report

**Pull request merged**
