### PR TITLE
Fix #3250: Invalid SPDX with empty file: no SHA1

### LINKED ISSUE #3250: Invalid SPDX with empty file: no SHA1
### Description

Generated SPDX is invalid as no SHA1 is provided.

```
FileName: ./phpwiki/blank.htm
SPDXID: SPDXRef-3
FileChecksum: SHA1:
LicenseConcluded: NOASSERTION
LicenseInfoInFile: NONE
FileCopyrightText: NONE
```

### How To Reproduce

```
svn checkout https://svn.code.sf.net/p/phpwiki/code/trunk phpwiki
```

```
./scancode -c -l -i --license-text --spdx-tv phpwiki.spdx phpwiki
```

### System configuration

```
./scancode --version
ScanCode version: 32.0.0rc1
ScanCode Output Format version: 3.0.0
SPDX License list version: 3.19
```
Ubuntu 22.10

### PR DESCRIPTION
**Pull request by vargenau**
Fixes #3250

### Tasks

* [x] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [x] Commits are in uniquely-named feature branch and has no merge conflicts 📁

Signed-off-by: Marc-Etienne Vargenau <marc-etienne.vargenau@nokia.com>

### CODE REVIEW

**Review by pombredanne — CHANGES_REQUESTED** [review]
Thanks! let's add a test to avoid any regression.

**Comment by vargenau** [comment]
I have added a test that is successful is ```tests/formattedcode/test_output_spdx.py```

However, some tests fails that seem unrelated. Can you please check?

**Review by AyanSinhaMahapatra — APPROVED** [review]
@vargenau LGTM! Thanks!

The test failures seem to be a heisenbug and happens in other PRs too sometimes, nothing related to this change ofc.

**Review by pombredanne — APPROVED** [review]
Thanks!

**Comment by AyanSinhaMahapatra** [comment]
@vargenau Thanks, merging!

**Pull request merged**
