### PR TITLE
Remove regular expression futurewarning

### LINKED ISSUE #2746: When running in Python 3.8*, a warning message occurs.
### Description

Warning message:
/cluecode/copyrights.py:3382: FutureWarning: Possible set difference at position 3
  remove_tags = re.compile(

### How To Reproduce
Run Scancode with Python 3.8.12

### System configuration
* What OS are you running on? (Windows/MacOS/Linux) : MacOS BigSur
* What version of scancode-toolkit was used to generate the scan file? 30.1.0
* What installation method was used to install/run scancode? (pip/source download/other) pip

### PR DESCRIPTION
**Pull request by soimkim**
Fixes #2746

### Tasks

* [x] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [x] Commits are in uniquely-named feature branch and has no merge conflicts 📁

### CODE REVIEW

**Review by pombredanne — APPROVED** [review]
Thank you ++
These are annoying alright!
(And happy new year!)

**Comment by soimkim** [comment]
Happy new year. 😄

**Comment by soimkim** [comment]
Dear @pombredanne , 
When will the next version of scancode-toolkit be released to pypi? 😃

**Comment by pombredanne** [comment]
@soimkim Hey!
this is happening just as we chat here!
I tagged a beta yesterday and I am in the process of publishing this beta release to GH and PyPI.
This is a beta1. I expect there will be a few extra beta releases over the next week or so and a few "rc" release candidates then

**Comment by pombredanne** [comment]
The goal of the betas is to make sure we can iron out all the small quirks that could be discovered.

**Comment by soimkim** [comment]
@pombredanne , awesome! 
I look forward to the release of scancode-toolkit.

**Pull request merged**
