### PR TITLE
Issue : #1378

### PR DESCRIPTION
**Pull request by Sarah0711**
Added new license and rule for Service Component Architecture JavaDoc, Interface Definition files and XSD files

Signed-off-by: sarkhan <sarkhan@adobe.com>

### CODE REVIEW

**Comment by Sarah0711** [comment]
Hi ,
Can anyone guide me as to what I am doing wrong?

Thanks,
Sarah

**Comment by ritiek** [comment]
@Sarah0711 It seems like you probably need to also add a short name, category and owner in [service-comp-arch.yml](https://github.com/nexB/scancode-toolkit/blob/7bb0ee1adaf9c864d8651596768dc152036f6972/src/licensedcode/data/rules/service-comp-arch.yml) for tests to pass. See other .yml files as reference.

**Comment by pombredanne** [comment]
@Sarah0711 thank you++ ! let me provide some in-line comments

**Comment by pombredanne** [comment]
@Sarah0711 yes, what @ritiek suggested is exactly what would be needed

> It seems like you probably need to also add a short name, category and owner in service-comp-arch.yml for tests to pass. See other .yml files as reference.

FWIW these are the checks done https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/models.py#L332 .

**Comment by Sarah0711** [comment]
Thanks @ritiek  ans @pombredanne  for your guidance, I will make the required changes .

**Comment by pombredanne** [comment]
@Sarah0711 Shall I go ahead and add missing details? or will you do it soon enough?
Thanks

**Comment by Sarah0711** [comment]
@pombredanne Sorry for the delay, I had some family emergency couldn't be online. I will be adding the missing details fast.

Thanks,
Sarah

**Comment by Sarah0711** [comment]
@pombredanne Changes have been done.

**Comment by pombredanne** [comment]
@Sarah0711 Thank you! I had missed that. Note that the category case  should be "Permissive" and not "permissive" hence the tests failures.... But I am merging and fixing it.

**Pull request merged**
