### PR TITLE
Fix cfg parsing #3008

### LINKED ISSUE #3008: Parsing issue in setup.cfg
### Description

> Parsing issue in setup.cfg

### How To Reproduce

```
[metadata]
name = build
version = 0.8.0
description = A simple, correct PEP 517 build frontend
long_description = file: README.md
long_description_content_type = text/markdown
author = Filipe Laíns
author_email = lains@riseup.net
license = MIT
license_file = LICENSE
classifiers = 
	License :: OSI Approved :: MIT License
	Programming Language :: Python :: 3
	Programming Language :: Python :: 3 :: Only
	Programming Language :: Python :: 3.6
	Programming Language :: Python :: 3.7
	Programming Language :: Python :: 3.8
	Programming Language :: Python :: 3.9
	Programming Language :: Python :: 3.10
	Programming Language :: Python :: Implementation :: CPython
	Programming Language :: Python :: Implementation :: PyPy
project_urls = 
	homepage = https://github.com/pypa/build
	changelog = https://pypa-build.readthedocs.io/en/stable/changelog.html

[options]
packages = find:
install_requires = 
	packaging>=19.0
	pep517>=0.9.1
	colorama;os_name == "nt" # not actually a runtime dependency, only supplied as there is not "recommended dependency" support
	importlib-metadata>=0.22;python_version < "3.8"
	tomli>=1.0.0;python_version < "3.11" # toml can be used instead -- in case it makes bootstrapping easier
python_requires = >=3.6
package_dir = 
	=src

[options.packages.find]
where = src

[options.entry_points]
console_scripts = 
	pyproject-build = build.__main__:entrypoint
pipx.run = 
	build = build.__main__:entrypoint

[options.extras_require]
docs = 
	furo>=2021.08.31
	sphinx~=4.0
	sphinx-argparse-cli>=1.5
	sphinx-autodoc-typehints>=1.10
test = 
	filelock>=3
	pytest>=6.2.4
	pytest-cov>=2.12
	pytest-mock>=2
	pytest-rerunfailures>=9.1
	pytest-xdist>=1.34
	toml>=0.10.0
	wheel>=0.36.0
	setuptools>=42.0.0;python_version < "3.10"
	setuptools>=56.0.0;python_version >= "3.10"
typing = 
	importlib-metadata>=4.6.4
	mypy==0.950
	typing-extensions>=3.7.4.3;python_version < "3.8"
virtualenv = 
	virtualenv>=20.0.35

[options.package_data]
build = 
	py.typed

[egg_info]
tag_build = 
tag_date = 0
```
Parse this cfg file with `SetupCfgHandler`. 

Expected : extracted_requirements should be like `packaging>=19.0`, 
Computed: extracted_requirements is `>=19.0`

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? Linux
* What version of scancode-toolkit was used to generate the scan file?
* What installation method was used to install/run scancode? source download

### PR DESCRIPTION
**Pull request by TG1999**
Signed-off-by: Tushar Goel <tushar.goel.dav@gmail.com>

Fixes #3008 

### Tasks

* [x] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [x] Commits are in uniquely-named feature branch and has no merge conflicts 📁

### CODE REVIEW

**Review by pombredanne — CHANGES_REQUESTED** [review]
Thanks!
Do you mind to also add a tests?

**Comment by pombredanne** [comment]
This is also failing these:
2022-06-30T15:34:59.4438826Z FAILED tests/packagedcode/test_plugin_package.py::TestPlugins::test_package_command_scan_python

> 
> 2022-06-30T15:34:59.4439263Z FAILED tests/packagedcode/test_pypi.py::TestPyPiPipfile::test_pipfile_lock_sample1
> 2022-06-30T15:34:59.4439775Z FAILED tests/packagedcode/test_pypi.py::TestPyPiPipfile::test_pipfile_lock_sample2
> 2022-06-30T15:34:59.4440194Z FAILED tests/packagedcode/test_pypi.py::TestPyPiPipfile::test_pipfile_lock_sample3
> 2022-06-30T15:34:59.4440631Z FAILED tests/packagedcode/test_pypi.py::TestPyPiPipfile::test_pipfile_lock_sample4
> 2022-06-30T15:34:59.4441046Z FAILED tests/packagedcode/test_pypi.py::TestPyPiPipfile::test_pipfile_lock_sample5

**Comment by pombredanne** [comment]
ping

**Comment by TG1999** [comment]
closing in lieu of this https://github.com/nexB/scancode-toolkit/commit/1862c2bfd7f22dde43f8dca6c32bec1bd1a1a4f5

**Pull request closed without merging**
