### PR TITLE
 Fix error count in report summary #938

### PR DESCRIPTION
**Pull request by techytushar**
PR for the issue #938 
Signed-off-by: Tushar Mittal <chiragmittal.mittal@gmail.com>

### CODE REVIEW

**Comment by yash-nisar** [comment]
Can you squash your commits @techytushar ?

**Comment by techytushar** [comment]
@yash-nisar i have squashed the commits, please help me in adding the tests 😅

**Comment by pombredanne** [comment]
Looking good!

test-wise this would be a test in test_cli.py
And the assertion should be made on the result.output ensuring it contains the correct string for counts (e.g. not `Errors count:   0` but a correct number and the data used for the test scan should have some errors.

**Comment by yash-nisar** [comment]
@techytushar Let me know if you have difficulties implementing the tests :) I'll add them and include your commit in my PR if you're okay with it.

**Comment by techytushar** [comment]
@pombredanne please review :smile:

**Comment by pombredanne** [comment]
@techytushar it took me a while to merge this... it is now done. Thanks for this!

**Pull request merged**
