### PR TITLE
Update License Policy Plugin

### PR DESCRIPTION
**Pull request by majurg**
* License Policy Plugin updated to use new policy file schema
* Handle policy files with duplicate license_key entries
* Log a warning to codebase.errors when dupes occur
* Re-structure plugin logic and add tests

Previous Tickets: #214, #880

Signed-off-by: Steven Esser <sesser@nexb.com>

### CODE REVIEW

**Comment by majurg** [comment]
@pombredanne Not sure if we want to log a Warning at the Codebase or Resource (`scan_error`) level. 

I chose Codebase level for now, as to not spam the message into each resource. The downside of this is the error messaging at the Codebase level isnt very informative:
```
Scanning done.
Some files failed to scan properly:
Warning: Duplicate License Policy entry for license_key: broadcom-commercial. Using first occurance by default.
Summary:        info, licenses with 1 process(es)
Errors count:   1
Scan Speed:     2.40 files/sec. 9.75 KB/sec.
Initial counts: 7 resource(s): 5 file(s) and 2 directorie(s) 
Final counts:   7 resource(s): 5 file(s) and 2 directorie(s) for 20.35 KB
Timings:
  setup_scan:licenses: 3.63s
  setup: 3.63s
  scan: 2.09s
  total: 5.74s
```

Not sure if this is the right way or not.

**Comment by pombredanne** [comment]
@majurg Thanks. IMHO a duplicated policy entry should be caught early and fail loudly. It should be checked possibly an `is_enabled`time and it should fail and stop the scan run.

**Comment by pombredanne** [comment]
And you still have a few tests failing.

**Comment by pombredanne** [comment]
Thanks. Looking good and merging.

**Pull request merged**
