### PR TITLE
dwarf test failure #1752 

### PR DESCRIPTION
**Pull request by linexb**
Fix the error of dwarf3 test case.

### CODE REVIEW

**Comment by majurg** [comment]
@linexb Your branch fixes all those `test_dwarf3.py` tests correctly, but I am still getting this final one: `FAILED plugins/scancode-compiledcode/tests/test_elf.py::TestScanPluginELFScan::test_elf_needed_library` in `test_elf.py`

**Comment by linexb** [comment]
I tried to run this on another laptop today, but I can't reproduce it. I have discussed with Steven on this again, and he will help me run a merge of the fix to his branch and run the CI to test. Thank you. @majurg

**Comment by majurg** [comment]
@linexb See https://dev.azure.com/nexB/scancode-toolkit/_build/results?buildId=1203&view=logs for the test_elf error I have been mentioning. Looks like the CI system is experiencing the same error I am locally.

**Comment by linexb** [comment]
@majurg  As discussed, the elf issue should be a Linux 32bit/64bit binary issue, I have opened a ticket for this: https://github.com/nexB/scancode-toolkit/issues/1762

Regarding to the dwarf error fix, are you OK with this before sending to @pombredanne  for review.

**Comment by majurg** [comment]
@linexb These changes fix the problems I was having with `test_dwarf3.py`. Along with https://github.com/nexB/scancode-toolkit/pull/1764, merging these commits will make all the `scancode-compiledcode` tests pass.

**Comment by pombredanne** [comment]
@linexb  thanks! 
there is one commit that is missing the DCO signoff... but I will merge anyway

**Pull request merged**
