### PR TITLE
#194 adding a new rule to detect GPL license with no version

### PR DESCRIPTION
**Pull request by rakeshbalusa**
New rule to detect the license `GPL` with no version is added. Added this license to a few tests which has the same text.

### CODE REVIEW

**Comment by pombredanne** [comment]
Thank you!
I would need to get more details on these other tests that had the same text to make sure we are not introducing biases. Same text may not mean this is always a valid mention.
Could you paste links to the each corresponding test file snippet lines?

**Comment by rakeshbalusa** [comment]
These are the `test files` with the same text which : 
- `https://github.com/nexB/scancode-toolkit/blob/develop/tests/licensedcode/data/licenses/adobe-air-sdk.txt#L18`
- `https://github.com/nexB/scancode-toolkit/blob/develop/tests/licensedcode/data/licenses/gpl-2.0-plus_and_gpl-2.0-plus_and_lgpl-2.1-plus_and_mpl-1.1_and_other.txt#L80`
- `https://github.com/nexB/scancode-toolkit/blob/develop/tests/licensedcode/data/licenses/bsd-new_53.txt#L38`

**Comment by pombredanne** [comment]
Thanks: so this is about Debian packaging. Let me pounder this a bit.

**Comment by pombredanne** [comment]
It would have been best to have individual commit for each test or change in the future.

**Pull request merged**
