### PR TITLE
Added Cockroach Community License with tests

### PR DESCRIPTION
**Pull request by nanspro**
Signed-off-by: Rahul Bishnoi  rahulbishnoi3636@gmail.com

### CODE REVIEW

**Comment by nanspro** [comment]
@pombredanne  this is my first PR in scancode 
How would you like to comment on this 
P.S I am expecting changes

**Comment by nanspro** [comment]
@pombredanne  can you review this now?

**Comment by pombredanne** [comment]
@nanspro sure, but you closed it... I guess you want to resubmit?

**Comment by pombredanne** [comment]
One note on the commit subject:
rather than:
`Added Cockroach Community License with tests`

use 
`Add Cockroach Community License with tests` 

.... using the imperative style, as if you were giving an order to the codebase to update itself!

Also when there is a ticket, please suffix you subject with the ticket number as this:

`Add Cockroach Community License with tests #858` 

This helps have nice hyperlink references between commits and tickets!

**Pull request closed without merging**
