### PR TITLE
Fix typos and enhance README.rst

### PR DESCRIPTION
**Pull request by all3fox**
* Fix bwlow -> below
* Make many directories render as code
* Add a reference to Comprehensive Installation section
* Fix "Done! -> ... and you are done!" as in the existing FAQ
* Fix articles and some minor grammar (sorry, couldn't stop)

Signed-off-by: Aleksandr Lisianoi <all3fox@gmail.com>

[skip ci]

You can see a rendered version here:

https://github.com/all3fox/scancode-toolkit/tree/docfix#scancode-toolkit

### CODE REVIEW

**Comment by all3fox** [comment]
Looks like this shoud be merged first:

https://github.com/nexB/scancode-toolkit/pull/569

Will then rebase and fix conflicts, if any.

**Comment by pombredanne** [comment]
Thanks for reminding me to merge #569 and yes it created a conflict. LGTM otherwise! Thanks.

**Comment by all3fox** [comment]
Done rebasing, accidentally rebased of `master` first and was very much surprised. Then realised, that the main branch is `develop` here. The #569 changed README.rst a lot, so this PR became very small.

**Comment by pombredanne** [comment]
Thanks ++

**Comment by pombredanne** [comment]
Now this is merged so it is too late: ..... but what does the `[skip ci]` in your commit comment means?

**Comment by all3fox** [comment]
@pombredanne it explicitly tells CI servers not to run any tests (travis skips the tests, and so does gitlab CI, most likely other CIs too). I did that because it is just a readme/doc change.

**Pull request merged**
