### PR TITLE
Adopt a code of conduct #301 

### PR DESCRIPTION
**Pull request by inishchith**
@pombredanne in reference to thread #898 .

### CODE REVIEW

**Comment by pombredanne** [comment]
Thanks! let paste here the previous comments

**Comment by pombredanne** [comment]
@SaravananOffl @sschuberth @haikoschol @majurg @mjherzog @jpopelka @JonoYang @jdaguil I need your feedback to see if you agree with the new code of conduct. I do 👍

-   @mjherzog commented 9 days ago https://github.com/nexB/scancode-toolkit/pull/898#issuecomment-364178909
The code seems to need a specific email address for reporting issues. Not sure what that would be.

-  @sschuberth 9 days ago  https://github.com/nexB/scancode-toolkit/pull/898#pullrequestreview-95166828
   - Is accepting a PR which exposes the email address as part of the Git history explicit permission?
   - @pombredanne 8 days ago Of course not... :) but you have a good point. I would be reluctant to change this standard CoC though after all this is only a template and we can make clear

- @sschuberth   9 days ago https://github.com/nexB/scancode-toolkit/pull/898#pullrequestreview-95167365 This needs to be filled out.
 ` +be reported by contacting the project team at [INSERT EMAIL ADDRESS]. `

- @sschuberth 9 days ago https://github.com/nexB/scancode-toolkit/pull/898#pullrequestreview-95167926  I would make clearer that not providing a response, e.g. in case of trolling, is also an option.

```
+Instances of abusive, harassing, or otherwise unacceptable behavior may
+be reported by contacting the project team at [INSERT EMAIL ADDRESS].
+All complaints will be reviewed and investigated and will result in a
+response that is deemed necessary and appropriate to the circumstances.
```

-  @majurg commented 9 days ago https://github.com/nexB/scancode-toolkit/pull/898#issuecomment-364251713 @pombredanne +1 from me, after @inishchith or others make the needed changes in the text

- @SaravananOffl commented 8 days ago https://github.com/nexB/scancode-toolkit/pull/898#issuecomment-364333939 @pombredanne +1 from me!

- @JonoYang commented 8 days ago https://github.com/nexB/scancode-toolkit/pull/898#issuecomment-364519510 @pombredanne 👍 after the changes

**Comment by sschuberth** [comment]
@pombredanne, I agree with the basic wording, but I still would like to see my comments addressed / the gaps filled after merging this in.

**Comment by mjherzog** [comment]
I agree that not responding needs to be an option, but not sure about the best way to clarify that point

**Comment by sschuberth** [comment]
Or maybe simply go with https://www.contributor-covenant.org/, which seems to be what "everybody" is using by now?

**Comment by mjherzog** [comment]
Since we have not been using project-based emails that seems to be the main outstanding issue.  I would argue that the language about "a response that is deemed necessary and appropriate to the circumstances" is broad enough to include the equivalent of no response other than to investigate the complaint.

**Comment by majurg** [comment]
@pombredanne From reading @mjherzog above comment, I think this can be merged.

**Comment by pombredanne** [comment]
This has been merged at last with https://github.com/nexB/scancode-toolkit/commit/af66ca22af6d421169009903b295be1fc0177c7b ... Closing now
Thank you ++

**Pull request closed without merging**
