### PR TITLE
Add missing package version for go.mod files

### LINKED ISSUE #2438: Go Parser missing Package Version for go.mod files
### Description

The Go parser for dependency files does not include package_version in the purl; version is included in the purl for go.sum files.

### System configuration

This is an issue for SCTK v21.2.9.

### PR DESCRIPTION
**Pull request by Divyansh2512**
Signed-off-by: Divyansh Sharma <2512sharmadivyansh@gmail.com>

Fixes #2438

Update golang parser to add missing package version in purl.

### Tasks

* [x] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [x] Commits are in uniquely-named feature branch and has no merge conflicts 📁

### CODE REVIEW

**Review by rpotter12 — APPROVED** [review]
All green. LGTM.....

@pombredanne Please review and merge.:)

**Comment by Divyansh2512** [comment]
@pombredanne @majurg kindly review!

**Review by steven-esser — COMMENTED** [review]
@Divyansh2512 This seems trivial enough change, but I wonder why it was not included in the initial implementation. 

I will defer to @JonoYang, as he has the most experience on the go package parsing.

**Comment by JonoYang** [comment]
@Divyansh2512 The changes look good. Thank you!

@majurg We didn't add the version to the purls of dependencies because not all dependencies for a package have a solid version number. This is the case of npm of pypi dependencies, where a range may be stated. However, in the case of go packages, an exact version is stated for dependencies in go.mod/go.sum files. It makes sense in this situation to report the dependency version as well.

**Pull request merged**
