### PR TITLE
Fixed inconsistency in --html-app FILE in cli-reference

### LINKED ISSUE #2789: Inconsistency in documentation of `--html-app FILE` in Command Line Interface Reference
### Description

> Incorrect command line input while describing ``html-app`` under the **Scancode Output Formats** label in Command Line Interface Reference. 

##### Given:

> scancode -clpieu --csv output.html samples

##### Correct command line input:

> scancode -clpieu --html-app output.html samples

### Link to Documentation Page

> https://scancode-toolkit.readthedocs.io/en/latest/cli-reference/output-format.html#html-app-file

### Select Category

-  [X] Inconsistency
-  [ ] New Section Request
-  [ ] General Improvement
-  [ ] Typo/Mistakes
-  [ ] Other

### PR DESCRIPTION
**Pull request by maynaS**
Fixes #2789

### Before
```scancode -clpieu --csv output.html samples```

### After
```scancode -clpieu --html-app output.html samples```

### Tasks

* [X] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [X] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [ ] Commits are in uniquely-named feature branch and has no merge conflicts 📁
It is a small documentation change, therefore I pushed it to the develop branch itself.

### CODE REVIEW

**Review by pombredanne — CHANGES_REQUESTED** [review]
@maynaS Thank you ++
You need to format you signoff, it must be on the last line of your commit message.
Also do you mind to squash all in a single clean commit with a single clean message?

**Comment by pombredanne** [comment]
Thanks! Do you mind to squash your commits in a single one with 
A subject that's less than 50 characters
A signoff on the last line of the message

**Comment by maynaS** [comment]
@pombredanne Hey, can you check it out? I have done what you asked for

**Review by pombredanne — APPROVED** [review]
Thank you ++
LGTM, merging!

**Pull request merged**
