### PR TITLE
Update the correct wording for license category

### PR DESCRIPTION
**Pull request by chinyeungli**
#408 

Changes
```
category: Attribution Restricted
category: Atribution
```
to
```
category: Free Restricted
category: Permissive
```

### CODE REVIEW

**Comment by pombredanne** [comment]
@chinyeungli Thank you!
This make a lot of sense as `permissive` is much more prevalent than `attribution` as a categorization for licenses. 
I may rebase this on the latest develop and there is a minor failure in `test_scan_can_return_matched_license_text` that I will investigate.

**Comment by pombredanne** [comment]
@chinyeungli Thank you!
This make a lot of sense as `permissive` is much more prevalent than `attribution` as a categorization for licenses. 
I may rebase this on the latest develop and there is a minor failure in `test_scan_can_return_matched_license_text` that I will investigate.

**Comment by pombredanne** [comment]
Actually forcing a rebuild solved things... This was an heisenbug ;)

**Comment by pombredanne** [comment]
@chinyeungli I am reviewing this... but there are no changes? May be you forgot to push them?

**Comment by chinyeungli** [comment]
@pombredanne my bad.. code pushed.

**Pull request merged**
