### PR TITLE
cli: Clarify how default command line options are enabled

### PR DESCRIPTION
**Pull request by sschuberth**

### CODE REVIEW

**Comment by pombredanne** [comment]
Good catch. This was not enough indeed. In fact I truly think that all scans may be best always enabled by default and that if you pass a specific scan option, then only that scan would be used.
Now to for this to be practical #384 would need to be there first as otherwise there are cases not so uncommon where you end up with data files with 1000's of urls or emails and that does not make sense to capture them all by default.

**Comment by pombredanne** [comment]
Merging.... Thanks!  .... btw @sschuberth do you want commit rights directly on the repo? that could make it easier? your call! you definitely earned it in any case.

**Comment by sschuberth** [comment]
> do you want commit rights directly on the repo?

I'd indeed appreciate that as it would simply the workflow a bit by me creating branches in your repo instead of my fork.

**Comment by pombredanne** [comment]
@sschuberth great. Invite sent! :bowing_man:

**Comment by pombredanne** [comment]
of note: force pushing is disabled/protected (for everyone) on the `master` and `develop` branches for sanity. This is fair game in any other branches otherwise.

**Comment by sschuberth** [comment]
Sure thing!

**Comment by pombredanne** [comment]
This is just an FYI... force pushing would fail if attempted on `master` and `develop` :)

**Comment by pombredanne** [comment]
even by me... I do not trust me in particular ;)

**Pull request merged**
