### PR TITLE
Load notice text from NOTICE file

### PR DESCRIPTION
**Pull request by sschuberth**
Please have a look at the individual commit messages for the details.

### CODE REVIEW

**Comment by pombredanne** [comment]
Thanks. Let me review tomorrow.

**Comment by pombredanne** [comment]
I am rebasing and merging this. Thanks!

**Comment by pombredanne** [comment]
These were merged with https://github.com/nexB/scancode-toolkit/commit/c6deda713d97dbb0e619ff83ad686a6d5f6ad8b7  https://github.com/nexB/scancode-toolkit/commit/0440d6094438e2d73b83e9925db16e2a3ec48633 and https://github.com/nexB/scancode-toolkit/commit/67548522d09a7f46529d5c4dd3fc6e454b6271b3

Thanks!

**Comment by pombredanne** [comment]
There are some issue with loading the NOTICE file text when scancode is built as a wheel, as the root directory is not the same as the project directory. I will have to amend this somehow.

**Comment by sschuberth** [comment]
Sorry for that. I wasn't even aware that ScanCode might be built as a wheel.

**Pull request closed without merging**
