### PR TITLE
fix docstring in debian_copyright.py

### LINKED ISSUE #2771: Correct code and/or docstrings or both
In get_primary_license, the docstring is not correct,
The text says:
```
Return a license expression string which is the primary license for the
debian copyright file.
```
but nothing is returned

https://github.com/nexB/scancode-toolkit/blob/1fdf40faabc0cf91fb3e7e8ff11412fcfb358577/src/packagedcode/debian_copyright.py#L374

### PR DESCRIPTION
**Pull request by adityasangave**
Fixes #2771 

### Tasks

* [x] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [x] Commits are in uniquely-named feature branch and has no merge conflicts 📁

### CODE REVIEW

**Review by pombredanne — CHANGES_REQUESTED** [review]
Thanks! Good catch. Actually you should go further and rename the function to `set_primary_license` because the function is not "getting" anything.

And then the docstring becomes something such as:
```
Compute and set the primary license expression of this
debian copyright file to`primary_license`
```

**Comment by adityasangave** [comment]
Sure I'll make these changes

**Comment by mjherzog** [comment]
Can we change the program name to spell debian correctly?

**Comment by adityasangave** [comment]
Oh my bad I'll correct this after making changes

**Review by pombredanne — APPROVED** [review]
Thanks!
LGTM... merging!

**Pull request merged**
