### PR TITLE
Support multiple input path in CLI #875 #1397

### PR DESCRIPTION
**Pull request by pombredanne**
This adds support for #875 #1397 aka. multiple inputs and a new `--include` option. 
* you can now enter multiple input paths with the constraint that they all must be relative path and share a common root directory.
* also add a new enabling option for `--include` that works in tandem with the `--ignore` and has the same semantics. Includes are processed first then ignores are applied on top.
* it is now possible to run this:
`find samples/ | grep zlib |grep -v ada | grep -v iostrea | xargs scancode  --include="*JGroup*" --ignore "*.S" --json-pp -` 
or this:
`git diff --name-only master | xargs scancode -i --json-pp -`

Reported-by: Nico Bucher @nicobucher
Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>

### CODE REVIEW

**Comment by pombredanne** [comment]
@nicobucher ping... were you able to test this branch a bit? feedback is mucho welcomed!

**Comment by nicobucher** [comment]
Hi @pombredanne, I was able to quickly try this out.
It seems to do exactly what I was looking for!

I will play around with this branch in the next days. Perhaps I can give more detailed feedback then.

**Comment by pombredanne** [comment]
@nicobucher thank you for the feedback. Note that the current implementation is subpar performance wise because the logic goes this way:
1. find what is the root, shared ancestor directory of all the files arguments (and they must all be relative paths)
2. walk the whole tree for this
3. keep only the ones that match the requested paths.

If you have a large codebase (say a Linux kernel) and you modified only one file, this would walk 70K files first. So this can be optimized later if needed.

**Comment by pombredanne** [comment]
@johnmhoran I moved the script to create one SPDX doc per license to this branch... https://github.com/nexB/scancode-toolkit/pull/1399/files#diff-09a4d8eb1415f0acf8c0e24ec59fc3d3

**Comment by johnmhoran** [comment]
Thanks for the heads-up @pombredanne .

**Comment by pombredanne** [comment]
All green ... merging now.

**Pull request merged**
