### PR TITLE
Rename precise_license_detection field #2967

### PR DESCRIPTION
**Pull request by JonoYang**
This PR renames the field `precise_license_detection` from the license scoring plugin to `identification_precision`, which is the original intended name for the field.

### CODE REVIEW

**Review by AyanSinhaMahapatra — APPROVED** [review]
Looks great!

But since we are changing the output format, we need to update it according to this https://scancode-toolkit.readthedocs.io/en/latest/misc/versioning.html btw, the format is [here](https://github.com/nexB/scancode-toolkit/blob/develop/src/scancode_config.py#L87) and add a changelog :P

**Comment by JonoYang** [comment]
@AyanSinhaMahapatra Thanks! I knew I was missing something

**Comment by JonoYang** [comment]
@AyanSinhaMahapatra @pombredanne 

I've updated the changelog with a list of the the new fields that we are using to replace the old field with in the license clarity score and summarizer plugins. Should I also bump the json output version here as well, or are we going to do that when we finalize the 31.0.0 release?

**Review by pombredanne — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
