### PR TITLE
If the platform is unsupported, actually disclose its name

### PR DESCRIPTION
**Pull request by sschuberth**
This is useful to know for debugging.

### CODE REVIEW

**Comment by pombredanne** [comment]
Looking thanks....  a minor comment: if you use `%r` instead of `"%s"` you will get the same effect with a slightly improved readability (`%r` is to get the "representation" of an object, which in cases of a string will be a quoted string.)

**Comment by pombredanne** [comment]
Just curious: which OS/arch combo did scancode fail on?

**Comment by sschuberth** [comment]
"win64", as I accidentally had the 64-bit version of Python in PATH. Likewise just curious, when will ScanCode run with 64-bit Python on Windows?

**Comment by pombredanne** [comment]
running on 64bits should not be a big issue, this is just about recompiling all the thirdparty and ensuring the tests pass: I have started working on getting 64 bits Python wheels here https://github.com/pombreda/thirdparty to have a fully automated rebuild of all thirddparties. There are some of them that can compile only under Mingw and I did not come down to these yet. If you are interested to chip in I could guide you alright.  This is is mostly about native libraries and testing: the candidates are likely libarchive, libmagic and 7zip and it is very possible that no recompilation is needed at all since these are either spawned (7zip) or use with a ctypes binding (libarchive, libmagic)

**Comment by pombredanne** [comment]
Merged with 6bbd4e5088f15ca082682a112eecc246e39ba880
Thank you!

**Pull request closed without merging**
