### PR TITLE
#447 restore default behavior of v1.x to return a root path by default

### PR DESCRIPTION
**Pull request by pombredanne**
* the new option "--strip-root" does not add a root directory segment

Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>

### CODE REVIEW

**Comment by pombredanne** [comment]
@jdaguil @nspsjsu Ready for you to test!

**Comment by jdaguil** [comment]
@pombredanne LGTM! :star:

**Comment by pombredanne** [comment]
@sschuberth heads up! This is being merged tomorrow. Note that with #520 you should be able to have a config file that could always `--strip-root` if this is what you prefer.

**Comment by sschuberth** [comment]
Thanks for the notice. I'll take care of adding `--strip-root` on our side.

**Comment by pombredanne** [comment]
@sschuberth thank you for the quick reply! I can merge now then.

**Pull request merged**
