### PR TITLE
#475 Add SFL license rule

### LINKED ISSUE #475: Add `sfl-license` rule
```
    License:    This is free software; you can redistribute it and/or modify
                it under the terms of the SFL License Agreement as provided
                in the file LICENSE.TXT.  This software is distributed in
                the hope that it will be useful, but without any warranty.
```
The above license is detected as `"key":"lgpl-2.1","score":41.67`
The correct license should be `sfl-license`

### PR DESCRIPTION
**Pull request by yasharmaster**
Fixes #475 
Signed off by : Yash Sharma yasharmaster@gmail.com

@pombredanne please review

### CODE REVIEW

**Comment by yasharmaster** [comment]
@pombredanne I have added the test. Please review.

**Comment by pombredanne** [comment]
@yasharmaster Thanks. LGTM. I will merge once the CI tests are finished.

**Comment by pombredanne** [comment]
Merging

**Comment by pombredanne** [comment]
Do not forget for future commits to add a `Signed-off-by: Your Name  <YourMeail@you.com>`

**Pull request merged**
