### PR TITLE
Report extracted_requirement correctly

### LINKED ISSUE #2983: get_requires_dependencies gives out specifier in extracted_requirement
### Description

> Please leave a brief description of the bug or feature request:

get_requires_dependencies gives out specifier in extracted_requirement
https://github.com/nexB/scancode-toolkit/blob/aba31126dcb3ab57f2b885090f7145f69b67351a/src/packagedcode/pypi.py#L1152
It should return requirement instead of that

### How To Reproduce

Try to get dependencies from a wheel

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? Linux
* What version of scancode-toolkit was used to generate the scan file? 31.0.0b5
* What installation method was used to install/run scancode? source download

### PR DESCRIPTION
**Pull request by TG1999**
Signed-off-by: Tushar Goel <tushar.goel.dav@gmail.com>

Fixes #2983

### Tasks

* [x] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [x] Commits are in uniquely-named feature branch and has no merge conflicts 📁

### CODE REVIEW

**Comment by AyanSinhaMahapatra** [comment]
LGTM! Thanks.

**Review by pombredanne — APPROVED** [review]
LGTM :+1:

**Comment by pombredanne** [comment]
These test is failing likely from the updated results:
tests/packagedcode/test_pypi.py::TestPyPiEndtoEnd::test_package_scan_pypi_end_to_end

**Comment by pombredanne** [comment]
tests/packagedcode/test_pypi.py::TestPyPiEndtoEnd::test_package_scan_pypi_end_to_end is failing only in the CI. Merging anyway.

**Pull request merged**
