### PR TITLE
Added script for creating list of licenses from openhub.net

### PR DESCRIPTION
**Pull request by yudhik11**
@pombredanne I have added the script in etc/scripts and also the json object is now getting created by library of python itself

### CODE REVIEW

**Comment by pombredanne** [comment]
Thanks!... So you need a little of PEP8 formatting on this. Check also the contributing file for your commit message. With that done, the next step will be to then fetch the text for each license and save this in a .txt file named after its name. And also create a yaml file similar to the ones we use in https://github.com/nexB/scancode-toolkit/tree/develop/tests/licensedcode/data/licenses for each test file... you can pyut the name as a key for a start. Then run the license tests and they will fail... and you can then set the proper license key in the .yml file one by one

**Comment by yash-nisar** [comment]
@yudhik11 Are you still working on this one ?

**Comment by pombredanne** [comment]
Thanks. I restarted the stuck build job.

**Comment by yash-nisar** [comment]
@pombredanne Note that this is the same script I'm working on. I took it up because the assignee did not respond.

**Comment by yudhik11** [comment]
@yash-nisar I was working on this project but was stuck even with the help provided by @pombredanne.

I would love to give inputs and complete this alongside you, if you are

**Comment by yudhik11** [comment]
If you are interested *

**Comment by pombredanne** [comment]
Folks, then the right way is to work on it together! 👍 
This is not a competition, but this is all about collaboration!

**Comment by pombredanne** [comment]
FYI, I respun the build on mac

**Comment by pombredanne** [comment]
So I guess this stale now? unless @yash-nisar you want to pick this up?

**Comment by yudhik11** [comment]
@pombredanne  sorry for replying late, but I talked to yash-nissar and he was not sure whether he would like to work together so I could not start working with him.

**Comment by majurg** [comment]
@yudhik11 @yash-nisar @pombredanne Ping to all. Not sure of the status of this. If no more work will be done, I will close this.

**Comment by pombredanne** [comment]
I am closing this for now since this is stale. Thank you ++ for trying!

**Pull request closed without merging**
