### PR TITLE
Update Regex to detect subsidiaries.

### LINKED ISSUE #2420: Incomplete copyright detected
`Copyright (c) 2009, 2018 Robert Bosch GmbH and its subsidiaries. ` is detected only as `"Copyright (c) 2009, 2018 Robert Bosch GmbH"`

### PR DESCRIPTION
**Pull request by akugarg**
Signed-off-by: akugarg <akanksha.garg2k@gmail.com>

Fixes #2420

### Tasks

* [x] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [x] Commits are in uniquely-named feature branch and has no merge conflicts 📁

### CODE REVIEW

**Comment by akugarg** [comment]
Hey! @pombredanne @majurg  Please review this.

**Review by pombredanne — CHANGES_REQUESTED** [review]
Thanks! That's likely the simplest, perfect and minimal fix to the problem. Yet I would need a proof of this in the form of a passing test!
Do you mind adding one?

**Comment by akugarg** [comment]
@pombredanne Thanks for your review. I will make the requested changes.

**Review by pombredanne — APPROVED** [review]
Looking great!
Thank you ++

**Pull request merged**
