### PR TITLE
Added new licence rules from licensebuttons.net

### LINKED ISSUE #1983: Add license detection rules for https://licensebuttons.net/
## Short Description
https://licensebuttons.net/ contains several buttons to CC licenses that are found as links often enough.
For instance https://licensebuttons.net/p/80x15.png or https://licensebuttons.net/l/GPL/2.0/88x62.png
Each such URL should be added as a license detection rule

## Possible Labels

- new feature

## Select Category

-  Enhancement [x]
-  Add License/Copyright [x]
-  Scan Feature []
-  Packaging []
-  Documentation []
-  Expand Support []
-  Other []

### PR DESCRIPTION
**Pull request by MankaranSingh**
Fixes #1983

### Tasks

* [x] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Rxun [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [x] Commits are in uniquely-named feature branch and has no merge conflicts 📁

I wrote a script for adding these changes, although, i have reviewed the changes manually, there may be some mistake.

I added most of the licence rules, but couldn't find existing licences for the following:

https://licensebuttons.net/l/devnations/
https://licensebuttons.net/l/nc-sa/
https://licensebuttons.net/l/nc-sampling+/
https://licensebuttons.net/l/nc-sampling/
https://licensebuttons.net/l/sa/
https://licensebuttons.net/l/zero/
https://licensebuttons.net/l/nd/
https://licensebuttons.net/l/nd-nc/
https://licensebuttons.net/l/nc/

Other than that, in existing licences, the 2.1 variant was not found in any of them, why so (j ust curious :) )  ?

### CODE REVIEW

**Comment by pombredanne** [comment]
Thanks! this looks perfect. There is one thing is that I pushed some commit with new rules that use the same names as yours. Do you mind to rename your files? Sorry for the trouble.

**Comment by pombredanne** [comment]
> Other than that, in existing licences, the 2.1 variant was not found in any of them, why so (j ust curious :) ) ?

Can explain what you mean?

**Comment by MankaranSingh** [comment]
@pombredanne  shall I add a 'license_button' prefix instead of a number for these ?  

> Can explain what you mean?

see these:
 - https://licensebuttons.net/l/by-nc-nd/2.1/
 - https://licensebuttons.net/l/by-nc/2.1/
 - https://licensebuttons.net/l/by-sa/2.1/ 

there are versions like 2.0, 2.5, 3.0, 4.0 but not 2.1 in any of the present licenses.

**Comment by pombredanne** [comment]
@MankaranSingh a `_licensebuttons` suffix is better IMHO

**Comment by MankaranSingh** [comment]
@pombredanne please see #1997 closing this one. II'l always try to work from a separate branch to avoid rebasing issues.

**Pull request closed without merging**
