### PR TITLE
Adding sample snap package

### LINKED ISSUE #1987: Sample snap package
## Possible Labels

- new feature

## Select Category

-  Packaging 

## **Describe the Update**

Update is regarding creation of snap packages for Linux distros for scancode-toolkit.

## **How This Feature will help you/your organization**
Snap is a package format similar to .rpm or .deb specifically created for snappy package manager.
It helps you to:
-build and then publish your snaps on the Snap store
-use channels, tracks and branches to finely control updates and releases
-build and debug snaps within a confined environment
-update and iterate over new builds without rebuilding the environment
-test and share your snaps locally.

## **Example/Links if Any**

https://snapcraft.io/docs/python-apps

## **Can you help with this Feature**

Yes

### PR DESCRIPTION
**Pull request by n1khilmane**
Fixes #1987 

### Tasks

* [x] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [ ] Commits are in uniquely-named feature branch and has no merge conflicts 📁

Signed-off-by: Nikhil Mane <nikhilmane1919@gmail.com>

### CODE REVIEW

**Comment by pombredanne** [comment]
Thank you! Do you mind to squash your commits and amend to add your DCO signoff to your commit message?

**Comment by n1khilmane** [comment]
> Thank you! Do you mind to squash your commits and amend to add your DCO signoff to your commit message?

I am facing some issues regarding the same , i tried `git rebase HEAD~4 --signoff` in the local branch. its an easy process, i don't know why there is an issue.

**Comment by Pratikrocks** [comment]
@n1khilmane , you can try by first squashing the 4 commits you have into a single commit locally, then you can force push that single commit .

**Comment by n1khilmane** [comment]
> @n1khilmane , you can try by first squashing the 4 commits you have into a single commit locally, then you can force push that single commit .

yeah its done. thanks!!

**Comment by n1khilmane** [comment]
@pombredanne what should be done for failing check?

**Comment by pombredanne** [comment]
@n1khilmane sorry for this late rely.. the failing is a fluke, you can ignore it. 

Now what can I do with this yaml file you kindly contributed? What is it used for?

**Comment by pombredanne** [comment]
I am closing this for now for lack of reply. Please submit a new PR if you want to finish this. Thank you!

**Pull request closed without merging**
