### PR TITLE
Fix for issue 1876 - Updated the batch file to replace "%" in arguments with an arbitrary …

### LINKED ISSUE #1876: Scanning a path with "%" fails on Windows
### Description

At least with ScanCode 3.0.2, scanning a path that contains "%" (the percent character) fails on Windows:

```
$ scancode --json-pp - --license NPM\%40xtuc\long\4.2.2\package.json
Usage: scancode [OPTIONS] <input> <OUTPUT FORMAT OPTION(s)>
Try 'scancode --help' for help on options and arguments.

Error: Invalid value for "input": Path "NPM\0xtuc\long\4.2.2\package.json" does not exist.
```

Note the `%40xtuc` in the input path vs. `0xtuc` in the error message.

Background: To guard against characters that are invalid / special on some file systems, [ORT](https://github.com/heremaps/oss-review-toolkit) percent-encodes charaters like `@` when downloading source code in order to scan it. At the example of the `long` NPM package version 4.2.2 from the `@xtuc` scope, it gets downloaded into a directory named "NPM\%40xtuc\long\4.2.2" where `@` is percent-encoded as `%40`.

### How To Reproduce

This can *only* be reproduced on *Windows*, it works on Linux. Also, I was only able to reproduce it with ScanCode version 3.0.2, as versions 3.1.x have [another issue](https://github.com/nexB/scancode-toolkit/issues/1875) on Windows.

1. Create a directory with "%40" as part of its name.
2. Create a file to scan within that directory.
3. Point ScanCode at that file to scan.

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? Windows 10 x64
* What version of scancode-toolkit was used to generate the scan file? 3.0.2
* What installation method was used to install/run scancode? Git

### PR DESCRIPTION
**Pull request by Duncan-Howe**
…placeholder "##PC##" during the "collectargs" routine and then restoring the "%" signs prior to passing to the scancode executable

Signed-off-by: Duncan Howe <duncan.howe@live.co.uk>

Fixes #1876

### Tasks

* [x] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [x] Commits are in uniquely-named feature branch and has no merge conflicts 📁

### CODE REVIEW

**Comment by sschuberth** [comment]
Hmm, maybe before trying to fix the logic to "collect all command line arguments in a variable" we should ask @pombredanne *why* this collecting is even necessary. More concretely, why don't we just use `%*` instead of creating `SCANCODE_CMD_LINE_ARGS`?

**Comment by pombredanne** [comment]
@Duncan-Howe Thank you ++
I wonder how to add a test for this?
@sschuberth I am no expert in batch files and cmd: this was to "slurp" arguments is as old as scancode itself.
If I recall correctly this is an idiom that I first saw in Tomcat https://github.com/apache/tomcat80/blob/trunk/bin/startup.bat#L47
I am fine with replacing this with anything that works nicely everywhere :)

**Comment by pombredanne** [comment]
For reference https://github.com/nexB/scancode-toolkit/issues/1876

**Comment by pombredanne** [comment]
@Duncan-Howe Do you mind to also update the changelog?

**Comment by Duncan-Howe** [comment]
@pombredanne What version number should I use as the heading for CHANGELOG or would vNext be OK?

**Comment by sschuberth** [comment]
> I am no expert in batch files and cmd: this was to "slurp" arguments is as old as scancode itself.

If the aim is to forward *all* args passed to the batch file, then IMO `%*` could be used and no complicated replacement of placeholders should be necessary. The story becomes more complicated if you want to forward e.g. all but the first argument, but this is not the case here AFAIU the code. BTW, the Tomcat code says to "Get remaining unshifted command line arguments", but there actually are no unshifted arguments before that line, so also the Tomcat code could be much simpler IMO. Tomcat probably also copied this from somewhere without exactly knowning what they are doing :wink:

**Comment by sschuberth** [comment]
So, @Duncan-Howe, would you mind giving the `%*` approach a try?

**Comment by Duncan-Howe** [comment]
@sschuberth Sure thing - I will refactor the batch file to use "%*" to pass the arguments through

**Comment by pombredanne** [comment]
> @pombredanne What version number should I use as the heading for CHANGELOG or would vNext be OK?

@Duncan-Howe Yes, that would work fine :+1:

**Comment by pombredanne** [comment]
> Tomcat probably also copied this from somewhere without exactly knowning what they are doing wink

I would call this me doing [cargo culting](https://en.wikipedia.org/wiki/Cargo_cult) at its best :D
This is 15 years old  :P https://github.com/apache/tomcat/blob/94400a237d15768ca227dd8c0f4dd5716b48e388/bin/startup.bat#L33

**Comment by Duncan-Howe** [comment]
Updated scancode.bat to remove a number of lines of code that weren't really doing much :-)
Now the arguments are passed straight through using the "%*" syntax so any number of arguments should work (validation of the arguments is delegated to the ScanCode executable)

**Comment by Duncan-Howe** [comment]
The updated batch file seems to perform in exactly the same way as previously when executed from ORT and produces the same result files for my own application scans

**Comment by sschuberth** [comment]
> The updated batch file seems to perform in exactly the same way as previously

Great! Thanks a lot for getting rid of this cruft in the batch file 😄

**Review by pombredanne — APPROVED** [review]
LGTM and merging now!
Thank you ++

**Pull request merged**
