### PR TITLE
Add CockroachDB Community License #858

### PR DESCRIPTION
**Pull request by yash-nisar**
Closes https://github.com/nexB/scancode-toolkit/issues/858

Signed-off-by: Yash Nisar <yash.nisar@somaiya.edu>

### CODE REVIEW

**Comment by yash-nisar** [comment]
@pombredanne Wanna have a look ?

**Comment by pombredanne** [comment]
Looking good. Thanks! I will merge when the tests are done

**Comment by yash-nisar** [comment]
Awesome, I shall ping you when the tests pass 👍

**Comment by yash-nisar** [comment]
@DennisClark Can you please help me out in figuring out the category of the license ?

**Comment by yash-nisar** [comment]
@pombredanne , I've asked for the category on their channel and they've categorised it as a "proprietary" license. You can have a look at the discussion [here](https://gitter.im/cockroachdb/cockroach?at=5a6b67fa494bd0f5302b48e8).

**Comment by pombredanne** [comment]
@yash-nisar Thanks++ .... could you add a test or two also? I am concerned that this license may trigger some false positive Apache detection since it also contains Apache references

**Comment by yash-nisar** [comment]
@pombredanne Please review. :)

**Comment by pombredanne** [comment]
Looking all good. Thank you again ❤️  merging

**Pull request merged**
