### PR TITLE
Added new checksum type for sha256

### LINKED ISSUE #1903: Add sha256 checksum for files
## Short Description
When doing a scan of a file, we get sha1 and md5 checksums:
```
  "files": [
    {
      "path": "bpftool",
      "type": "file",
      "name": "bpftool",
      "base_name": "bpftool",
      "extension": "",
      "size": 1137832,
      "date": "2019-04-17",
      "sha1": "ebc8038723944dac6aa184b9aeb84488be05062e",
      "md5": "f0c381c373fb110d2afbd8d9895f2a2f",
      "mime_type": "application/x-executable",
      "file_type": "ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, for GNU/Linux 3.2.0, BuildID[sha1]=9fecc3a68cf22ec489867811587268f35b8f924d, stripped",
      "programming_language": null,
      "is_binary": true,
      "is_text": false,
      "is_archive": false,
      "is_media": false,
      "is_source": false,
      "is_script": false,
```
It would be nice to add a sha256 checksum as well.
## Possible Labels

- new feature

## Select Category

-  Enhancement [x]
-  Add License/Copyright []
-  Scan Feature [x]
-  Packaging []
-  Documentation []
-  Expand Support []
-  Other []

## **Describe the Update**
Add a new checksum type for sha256

## **How This Feature will help you/your organization**
- If we do have files of known sha256 digests in a database somewhere, it would be easy to use scancode's file level inventory data rather than do the hashing ourselves.
- sha256 is probably the only digest used in cloud native.

## **Can you help with this Feature**
Of course! I will need some guidance on where to make the change though :)

### PR DESCRIPTION
**Pull request by nitish81299**
Signed-off-by: Nitish nitishkumar81299@gmail.com

Fixes #1903 

### Tasks

* [X] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [X] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://aboutcode.readthedocs.io/en/latest/scancode-toolkit/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [X] Commits are in uniquely-named feature branch and has no merge conflicts 📁

### CODE REVIEW

**Comment by nitish81299** [comment]
Screenshot_20200217_234423


*Here is the screenshot of the changes requested.*

**Comment by pombredanne** [comment]
@nishak FYI

**Comment by pombredanne** [comment]
@nitish81299 gentle ping

**Comment by pombredanne** [comment]
@nitish81299 Do you need some help to complete this?

**Comment by nitish81299** [comment]
@pombredanne sorry being inactive. 
I was having my exams. I'll try to cover it in 2-3 days.

**Comment by nitish81299** [comment]
@pombredanne have a look.
Some tests are failing but I don't know why.

**Comment by pombredanne** [comment]
@nitish81299 You did remove your clone, so it made merging a bit more difficult. I eventually used the patch and created this PR #2138 instead... so I am closing this one 
Thank you++

**Pull request closed without merging**
