### PR TITLE
Added basic plot of Doc

### PR DESCRIPTION
**Pull request by RituRajSingh878**
I have added a basic plot of Doc, and I will update this doc(I want to work in GSoD).
 ref #1570

### CODE REVIEW

**Comment by RituRajSingh878** [comment]
@mjherzog, please review it.

**Comment by RituRajSingh878** [comment]
It will look like -
doc

**Comment by DennisClark** [comment]
@RituRajSingh878  Thanks for this!   I'll be reviewing this ASAP and will get back to everyone.

**Comment by RituRajSingh878** [comment]
@DennisClark, please review this

**Comment by majurg** [comment]
@DennisClark Should this be moved to aboutcode? If so I will close and redirect the student to the proper location.

**Comment by majurg** [comment]
Changes incorporated by @AyanSinhaMahapatra via #27 and others. Closing this.

**Comment by majurg** [comment]
#1784 merged, closing this for now.

**Pull request closed without merging**
